### ISSUE TITLE
Сбрасываются сертификаты после перезагрузки роутера на Padavan

### ISSUE THREAD

**Issue by filutkie** [zhovner/zaborona_help#108]
После отключения роутера Mi Mini WiFi на Padavan и повторного включения, страница с сертификатами оказывается пустой и ее приходится заново заполнять вручную. 

Это какой-то баг в данной прошивке и это можно исправить или так оно у всех и придется смириться?

**Comment by advokatb** [comment]
**Дополнительно -> Администрирование -> Записать настройки во флеш-память сейчас**

**Comment by zhovner** [comment]
С этой проблемой необходимо обращаться к разработчикам вашей прошивки или спросит у авторов инструкции в wiki. В issues на github мы обсуждаем проблемы на нашей стороне.
