### ISSUE TITLE
Множество недоступных сайтов по указу СНБО

### ISSUE THREAD

**Issue by DJm00n** [zhovner/zaborona_help#110]
Пачка сайтов из списка "ЮРИДИЧНІ ОСОБИ, до яких застосовуються обмежувальні заходи (санкції)" http://www.rnbo.gov.ua/files/2018/dodatok_2.pdf не открываются в Украине. Можно ли их добавить в список zaborona?

**Comment by zhovner** [comment]
Кроме вебмани не увидел там сайтов. Если мы пропустили какие-то адрес, пиши в этот тикет https://github.com/zhovner/zaborona_help/issues/97

**Comment by DJm00n** [comment]
@zhovner Отписал там.
