### ISSUE TITLE
Добавить новые домены и субдомены в фильтр

### ISSUE THREAD

**Issue by AlexUnder2010** [zhovner/zaborona_help#113]
Готовится новый пакет блокировок. Ссылку на официальные документы оставляю ниже:
https://www.slideshare.net/mobile/TarasSidorzhevsky/scan0000-105724974?ref=https://ukranews.com/news/573608-v-ukrayne-zablokyruyut-eshhe-180-rossyyskykh-saytov

**Comment by zhovner** [comment]
Я не думаю, что есть смысл добавлять все-все сайты к нам, потому что это увеличивает число маршрутов, которые нужно анонсировать, а это число конечно. 

Мы ориентируется на сайты, которые нужны людям повседневно: почта, поисковик, социальные сети и т.д. Полагаю что на новостные сайты можно зайти из под TOR.

**Comment by AlexUnder2010** [comment]
Хорошо, пускай будет так
