### ISSUE TITLE
Добавить streamlabs.com

### ISSUE THREAD

**Issue by hahatulk** [zhovner/zaborona_help#116]
Здравствуйте, недавно был заблокирован сервис оповещений донатов и подписок для стримеров - streamlabs.com Сам сайт работает, а сервис - нет.
Пожалуйста, добавьте его в списки маршрутизации

**Comment by toxi22** [comment]
Здравствуйте.
Проблема еще актуальна?

**Comment by hahatulk** [comment]
Уже неактуально
