### ISSUE TITLE
drweb.ru add to list pls.

### ISSUE THREAD

**Issue by Challenger71** [zhovner/zaborona_help#117]
Здравствуйте!
Пожалуйста, добавьте в лист обхода **drweb.ru** и все его под-домены.
Заходит лишь через сторонние прокси. А скачивать загрузочный образ CureIt через медленный прокси - напрягает :)
Всё остальное отлично работает!

**Спасибо Вам за помощь простому народу!**

**Comment by zhovner** [comment]
drweb использует защиту от ddos компании qrator, мы не можем добавлять их сети себе, это захватывает слишком много других сайтов.
