### ISSUE TITLE
Ubuntu 18.04 утечка DNS

### ISSUE THREAD

**Issue by GoodGuyNick** [zhovner/zaborona_help#118]
В Ubuntu 18.04 с OpenVPN идёт утечка DNS, из-за чего нельзя обойти блокировки впном. Проблема на стороне убунты. Я не смог найти нормального решения проблемы, кроме как замены DNS на главном подключении.

**Comment by vstepaniuk** [comment]
@GoodGuyNick Вы просто прописали `74.82.42.42, 77.88.8.8` в строке Additional DNS servers для IPv4 основного подключения?

Прописать их только для VPN подключения не получится?

Вчера у меня (после прописывания DNS для разных подключений) вроде бы всё работало. Сегодня же без каких-либо изменений с моей стороны вдруг некторые сайты перестали работать. К примеру `vk.com` работает, а `yandex.ru` - нет. Даже после прописывания DNS для разных подключений.

Подскажите, что можно с этим сделать?

**Comment by zhovner** [comment]
покажите вывод  таких команд:

`dig +trace yandex.ru`

`traceroute yandex.ru`

**Comment by vstepaniuk** [comment]
```
$ dig +trace yandex.ru

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> +trace yandex.ru
;; global options: +cmd
;; Received 28 bytes from 127.0.0.53#53(127.0.0.53) in 0 ms
```

```
$ traceroute yandex.ru
traceroute to yandex.ru (127.0.0.1), 30 hops max, 60 byte packets
 1  localhost (127.0.0.1)  0.639 ms  0.593 ms  0.561 ms
```
I am doing it from Live USB with Ubuntu 18.04. Only the OpenVPN cofiguration file was imported and the "Use this connection only for resources on its network" option was checked - no DNS servers were mentioned manually. Zaborona.help works well on Windows 7 and Android on my network. Geographically I am located in Ukraine.

Let me know if you need any additional information.

**Comment by GoodGuyNick** [comment]
@vstepaniuk no, with Additional DNS servers it will not work properly. Here what I've did: 
Edit connection=>IPv4 Settings/IPv6 Settings
Method(IPv4): Automatic(DHCP) addresses only
Method(IPv6): Automatic, addresses only
DNS servers(IPv4): 1.1.1.1, 1.0.0.1
DNS servers(IPv6): 2606:4700:4700::1111, 2606:4700:4700::1001
DNS servers I use is [CloudFlare](https://1.1.1.1)

**Comment by zhovner** [comment]
Почему `yandex.ru` у вас резолвится на `127.0.0.1`? Это, наверное, блокировка провайдера на уровне DNS? Первая команда `dig +trace` должна была показать от какого именно DNS резолвера вы получаете ответ, но почему-то она у вас не сработала.

Очевидно, что проблема в DNS. Если ваш провайдера перехватывает DNS запрос и подменяет ответы, то установка `1.1.1.1`не решит проблему, так как запросы к этому серверу пойдут мимо VPN и их подменит провайдера. 

Вам нужно заворачивать DNS запрос в VPN тоннель. Адреса DNS которые выдает наш сервер `74.82.42.42 и 77.88.8.8` так же анонсируются и в маршрутах, чтобы запросы к ним шли именно через VPN а не через вашего провайдера. 

>Which connection method ("Automatic (DHCP)" or "Automatic (DHCP) addresses only") should be used with zaborona.help and why?
Я не знаю что в чем разница этих опций. 

Советую вам разобраться с командой dig и понять от какого DNS вы получаете ответы.

**Comment by abradabra** [comment]
Проблема есть из-за systemd-resolver, который по умолчанию в новых ubuntu.
Можно частично решить проблему через редактирование /etc/systemd/resolved.conf
Вписав туда что-то вроде:
[Resolve]
DNS=1.1.1.1
FallbackDNS=8.8.8.8

но если провайдер перехватывает DNS ответы, то тогда это не поможет.

**Comment by SergeiKaptelin** [comment]
Для Linux Mint 19.3 Tricia, что на базе Ubuntu 18.04 решение c добавлением DNS работает

![Снимок экрана от 2020-01-15 20-43-46](https://user-images.githubusercontent.com/23096274/72461943-b35e8080-37d8-11ea-96ac-dcdfad605907.jpg)
