### ISSUE TITLE
Провайдер начал блокировать ответы GoogleDNS

### ISSUE THREAD

**Issue by iG8R** [zhovner/zaborona_help#120]
С 16.08.2018 провайдер начал блокировать ответы от GoogleDNS - 8.8.8.8 и 8.8.4.4 потому пришлось все запросы к DNS завернуть через Zaborona, что IMHO, не есть хорошо.

Роутер Mikrotik:

[admin@MikroTik] > /ip dns print
servers: 8.8.8.8,8.8.4.4
dynamic-servers: 77.88.8.8,74.82.42.42
allow-remote-requests: yes
max-udp-packet-size: 4096
query-server-timeout: 2s
query-total-timeout: 10s
max-concurrent-queries: 100
max-concurrent-tcp-sessions: 20
cache-size: 2048KiB
cache-max-ttl: 1w
cache-used: 48KiB

 /ip route add dst-address=8.8.8.8/32 gateway=zaborona
 /ip route add dst-address=8.8.4.4/32 gateway=zaborona

Возможно ли как-то разрешить сложившуюся ситуацию, чтобы обойти возникшее ограничение?

ЗЫ. Пробовал также 1.1.1.1 и 1.0.0.1, но провайдер и их тоже фильтрует.

**Comment by zhovner** [comment]
Ваш провайдер, очевидно, перехватывает все DNS запросы а не только к определенным.
На забороне, на самом деле, используются те же `8.8.8.8`, потому что мы точно так же как ваш провайдер перехватываем все DNS запросы и часть из них подменяем для того, чтобы исправить проблемы с yandex. Подробнее можете почитать здесь:

[medium.com/@zaborona/решение-проблем-с-yandex-ua-и-mail-ru](https://medium.com/@zaborona/решение-проблем-с-yandex-ua-и-mail-ru-a954cae5156c)

И посмотреть на список подменяемых адресов здесь:

https://github.com/zhovner/zaborona_help/blob/master/config/dnsmasq.d/zaborona

>пришлось все запросы к DNS завернуть через Zaborona, что IMHO, не есть хорошо

Не знаю почему вы считаете, что использовать DNS через заборону плохо. Единственный минус который я могу понять, это долгое время ответа, по сравнению с запросами напрямую через провайдера.

Вы можете попробовать использовать dnscrypt. В нем DNS запросы запросы происходят в зашифрованном виде и провайдер не может подменить. Однако для этого потребуется держать запущенным специальный софт. Можно поднять на соседнем компьютере в локальной сети и отдавать его адрес в качестве резолвера. Не знаю выиграете ли вы что-то по скорости ответа по сравнению с DNS через заборону.

**Comment by iG8R** [comment]
Спасибо большое за столь развернутый ответ.
Из статьи "Решение проблем с Yandex.UA и Mail.ru" выяснил, что в моем случае вообще было очень странное поведение - при работающей Zaborone на "ping yandex.ua" выдывало адрес "5.255.255.60", но в то же время при попытке открыть сайт "yandex.ua" через браузер появлялась всё та же стандартная заглушка "Согласно указу 'Алчного животного' номер такой-то от числа такого-то сайт заблокирован".
И только при перенаправлении всех DNS запросов через Zaborony, путем прописывания
/ip route add dst-address=8.8.8.8/32 gateway=zaborona
/ip route add dst-address=8.8.4.4/32 gateway=zaborona
сайты стали открываться через браузер.
В то же время, ответы на "ping yandex.ua" как без перенаправления, так с перенаправлением всех DNS остались такими же - "5.255.255.60".
Однако, ответы на странице https://zaborona.help/dnstest.html были разными
- без перенаправления, писалось, что DNS сервера Zaborony не используются
- с перенаправлением всех DNS - "Используются DNS сервера Zaborona.help"

Как такое может быть, когда в ответ на пинг всегда был правильный адрес - 5.255.255.60?

Я считал, что перенаправление всех DNS запросов через Zaborony скажется на времени ответа, но по ощущениям, загрузка страниц даже ускорилась. В чем это выражается - часто пользуюсь QTranslate для помощи в переводе с китайского, часто переключаюсь между Google, Yandex и Baidu. Так вот, до того как перенаправил все DNS запросы, перевод часто поялвляся с существенной задержкой, особенно от Yandex и Baidu, и иногда даже с ошибкой, мол, данные от сервера неверные. Сейчас же, когда все DNS идут через Zaborony - переводы появляются практически мгновенно, даже доступ к Google-переводчику ускорился.

**Comment by zhovner** [comment]
>Как такое может быть, когда в ответ на пинг всегда был правильный адрес - 5.255.255.60?

Кеш dns?

**Comment by iG8R** [comment]
В том-то и дело, что всегда делал ipconfig /flushdns после смены DNS.
Да и если бы это был кэш DNS, то помимо пинга и страницы в браузере открывались, и https://zaborona.help/dnstest.html не изменял бы результаты тестирования, т.к. 5.255.255.60 всегда обрабатывался через Zaboronu.
Может провайдеры придумали какую-то очередную уловку?

**Comment by zhovner** [comment]
>Может провайдеры придумали какую-то очередную уловку?

Вряд ли, скорее всего вы просто чего-то не учли. В любом случае нет причин пытаться использовать DNS в обход забороны. Так что тут есть только одно правильное и рабочее решение.
