### ISSUE TITLE
Добавьте Rutracker.org

### ISSUE THREAD

**Issue by Agagamand** [zhovner/zaborona_help#121]
На Рутрекере уже давно прикрывают доступ к определённым раздачам при обращении правообладателей из СНГ. Не могли бы вы добавить этот трекер в список проксируемых через Американские сервера? Добавить нужно только сам сайт, анонсеры можно не трогать.

Пример заблокированной для СНГ раздачи: https://rutracker.org/forum/viewtopic.php?t=5514591

**Comment by toxi22** [comment]
А если зайти по доменному зеркалу? https://rutrackertr.cf/forum/viewtopic.php?t=5514591

**Comment by zhovner** [comment]
>проксируемых через Американские сервера

У нас только сервера в СНГ, иначе все жалуются на недоступную музыку и видео во вконтакте и яндексе.

**Comment by Agagamand** [comment]
Как это только в России? А это что, начиная со строчки # spotify.com, netflix.com? https://github.com/zhovner/zaborona_help/blob/master/config/dnsmasq.d/zaborona

**Comment by toxi22** [comment]
> Как это только в СНГ? А это что, начиная со строчки # spotify.com, netflix.com? https://github.com/zhovner/zaborona_help/blob/master/config/dnsmasq.d/zaborona

Это отправка запросов через сторонний прокси-сервер и отношения к Забороне этот прокси не имеет.
