### ISSUE TITLE
Не работает на linux mint 19 для Київстар (домашний интернет)

### ISSUE THREAD

**Issue by mubat** [zhovner/zaborona_help#122]
Добрый день.
Система не работает на linux mint 19. Провайдер Київстар (домашний интернет). При включенном VPN открывает страница провайдера с информацией о блокировке.
На этом же компьютере, но под Windows 10 всё работает как положено.

На linux использовал файлы _zaborona-help.ovpn_ и _srv8.zaborona-help.ovpn_.

**Comment by Pleskan** [comment]
Пропиши в настройках NetworkManager в Linux, любые другие альтернативные DNS.
Как это сделать — Гугл в помощь. Может помочь.

**Comment by mubat** [comment]
Поменял на сторонний DNS Level 3 Communications - пока полёт нормальный.
@Pleskan Спасибо.

**Comment by zhovner** [comment]
А все дело в том, что в линуксе есть проблема с установкой DNS резолверов которые предлагает сервер при подключении. Так как некоторые провайдеры, в том числе и Киевстар, перехватывают запросы к любым DNS серверам, мы заворачиваем запросы в тоннель, чтобы првоайдер их не видел и не смог подменить. Поэтому важно использовать именно наши DNS к которым анонсируется маршрут через VPN.
```
Первичный DNS: 74.82.42.42
Вторичный DNS: 77.88.8.8
```

Подробнее проблема описана здесь https://medium.com/@zaborona/%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC-%D1%81-yandex-ua-%D0%B8-mail-ru-a954cae5156c

**Comment by Pleskan** [comment]
@zhovner , а происходит это потому, что такая приблуда как NetworkManager по-умолчанию тянет DNS провайдера.

**Comment by zhovner** [comment]
@Pleskan Каждый линукс сломан по-своему. Я не берусь сказать в чем именно дело конкретно у @mubat 

Есть простой тест для определения используются ли наши DNS. 
Если ссылка открывается http://dns-test.zaborona/imgtest.gif?1537282778445 значит используются наши DNS. Чтобы исключить кеш браузера, можно после знака вопроса дописывать любые символы на каждый новый тест.

**Comment by mubat** [comment]
@Pleskan DNS я проставлял на роутере потому что когда менял в файле ` /etc/resolv.conf` DNS сервера, линукс обратно возвращал. На роутере же если менять, то работает.
Был ещё нюанс, что поставил какой-то DNS (не помню какой), и на ноутбуке с линксом VPN заработал, а на ПК из-под Windows интернет отвалился. С DNS Level 3 Communications на обоих машинах работает (пока).

**Comment by zhovner** [comment]
> С DNS Level 3 Communications на обоих машинах работает (пока).
Не знаю какой конкретно адрес DNS резолвера вы используете, но в любом случае, выполняя запросы мимо VPN тоннеля, вы рискуете получить не тот ответ который ожидаете. 

Кстати есть еще dnscrypt и dns over https, для решения тех же задач.

**Comment by Pleskan** [comment]
@mubat, > потому что когда менял в файле /etc/resolv.conf DNS сервера, линукс обратно возвращал.
Именно про это я и писал выше. 
@zhovner, да я в курсе, спасибо
