### ISSUE TITLE
Нет подключения

### ISSUE THREAD

**Issue by portotiv** [zhovner/zaborona_help#123]
Здравствуйте. Давно не пользовался вашим конфигом из за ненадобности. Теперь вот в єтом появилась необходимость, а подключение не идет.
Вот лог:
Sat Sep 29 14:13:34 2018 OpenVPN 2.4.5 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar  1 2018
Sat Sep 29 14:13:34 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Sat Sep 29 14:13:34 2018 library versions: OpenSSL 1.1.0f  25 May 2017, LZO 2.10
Enter Management Password:
Sat Sep 29 14:13:35 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.57.109:1194
Sat Sep 29 14:13:35 2018 Attempting to establish TCP connection with [AF_INET]94.242.57.109:1194 [nonblock]
Sat Sep 29 14:13:36 2018 TCP connection established with [AF_INET]94.242.57.109:1194
Sat Sep 29 14:13:36 2018 TCP_CLIENT link local: (not bound)
Sat Sep 29 14:13:36 2018 TCP_CLIENT link remote: [AF_INET]94.242.57.109:1194
Sat Sep 29 14:13:36 2018 [zaborona.help] Peer Connection Initiated with [AF_INET]94.242.57.109:1194
Sat Sep 29 14:13:37 2018 open_tun
Sat Sep 29 14:13:37 2018 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{65373033-0D39-4782-AC0D-861CD0A80CDD}.tap
Sat Sep 29 14:13:37 2018 Set TAP-Windows TUN subnet mode network/local/netmask = 192.168.224.0/192.168.224.118/255.255.252.0 [SUCCEEDED]
Sat Sep 29 14:13:37 2018 Notified TAP-Windows driver to set a DHCP IP/netmask of 192.168.224.118/255.255.252.0 on interface {65373033-0D39-4782-AC0D-861CD0A80CDD} [DHCP-serv: 192.168.227.254, lease-time: 31536000]
Sat Sep 29 14:13:37 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=1
Sat Sep 29 14:13:38 2018 NETSH: C:\Windows\system32\netsh.exe interface ipv6 set address interface=7 2a00:1838:30:7300::1074 store=active
Sat Sep 29 14:13:38 2018 ERROR: netsh command failed: returned error code 1
Sat Sep 29 14:13:43 2018 NETSH: C:\Windows\system32\netsh.exe interface ipv6 set address interface=7 2a00:1838:30:7300::1074 store=active
Sat Sep 29 14:13:43 2018 ERROR: netsh command failed: returned error code 1
Sat Sep 29 14:13:48 2018 NETSH: C:\Windows\system32\netsh.exe interface ipv6 set address interface=7 2a00:1838:30:7300::1074 store=active
Sat Sep 29 14:13:49 2018 ERROR: netsh command failed: returned error code 1
Sat Sep 29 14:13:54 2018 NETSH: C:\Windows\system32\netsh.exe interface ipv6 set address interface=7 2a00:1838:30:7300::1074 store=active
Sat Sep 29 14:13:54 2018 ERROR: netsh command failed: returned error code 1
Sat Sep 29 14:13:58 2018 NETSH: command failed
Sat Sep 29 14:13:58 2018 Exiting due to fatal error

Где я мог накасячить?
Спасибо заранее.

**Comment by Radiokot** [comment]
Включен ли tap адаптер?
Центр управления сетями и общим доступом -> Изменение параметров адаптера.
![image](https://user-images.githubusercontent.com/5675681/46308892-86766200-c5c3-11e8-971c-1c26903ade9d.png)
Если "tap0" не горит синим включить его

**Comment by zhovner** [comment]
Проблема в ipv6, читайте это: https://github.com/zhovner/zaborona_help/wiki/%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%B1%D0%B5%D0%B7-IPv6
