### ISSUE TITLE
Dynamic DNS (Mikrotik)

### ISSUE THREAD

**Issue by baragoon** [zhovner/zaborona_help#129]
Доброе утро.
При использовании Вашего сервиса (отдельное спасибо) на микротике ovpn клиент "получает" от Вас динамические DNS сервера, которые, мягко говоря, портят работу сети. Я использую opendns для блокировки нежелательного контента в сети. Но, когда на роутере поднят коннект к Вам, часть запросов идет на резолв к 77.88.8.8 и 74.82.42.42. Возможности отключить их получение на роутере нет (привет, микротик). Приходится перенаправлять все запросы udp 53 при помощи НАТа. Выход, но костыльный. Можно ли перестать пушить эти сервера клиентам? Те, кому надо, могут их прописать ручками.
Спасибо.

**Comment by zhovner** [comment]
Множество провайдеров, например Киевстар, перехватывают DNS запросы и подменяют ответы на заглушку. Именно поэтому мы заворачиваем DNS запросы в VPN тоннель, чтобы провайдер не смог их подменить. Идея в том, что эти же адреса можно использовать и с тоннелем и без. Помимо этого, нам приходится выполнять подмену DNS ответов некоторых адресов yandex, чтобы решать проблему, когда сам яндекс пытается обойти блокировки, она описана здесь  https://medium.com/@zaborona/%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC-%D1%81-yandex-ua-%D0%B8-mail-ru-a954cae5156c

Ваша проблема решает установкой нужных DNS серверов в настройках DHCP сервера:
`IP -> DHCP Server -> networks`
Там можно установить произвольные DNS сервера которые будут выдаваться клиентам.

![image](https://user-images.githubusercontent.com/774290/50495651-88718500-0a3b-11e9-9032-568a94083027.png)

**Comment by baragoon** [comment]
> Ваша проблема решает установкой нужных DNS серверов в настройках DHCP сервера:
Речь шла о микротике в качестве клиента, а не сервера.
