### ISSUE TITLE
команды tool

### ISSUE THREAD

**Issue by publicav** [zhovner/zaborona_help#132]
чтото команды tolol правильно не отрабатываются  загрузил три файла ручками и где третий файл который называется ca.crt я то поднял  соеденение на новом микротике но проверить мне работу сложно сложновато.

**Comment by zhovner** [comment]
>и где третий файл который называется ca.crt
здесь все файлы сертификатов https://zaborona.help/extra.html

> команды tolol правильно не отрабатываются 
Что такое команды tolol?
