### ISSUE TITLE
Добавьте 5-tv.ru

### ISSUE THREAD

**Issue by Agagamand** [zhovner/zaborona_help#135]
Простой новостной сайт. Всё видео которое используется у них в новостях хранится на Ютубе, а значит особой нагрузки добавление этого сайта в список проксируемых не создаст.

**Comment by toxi22** [comment]
Сайты должны работать без проблем на конфигурации [zaborona-help_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/zaborona-help_maxroutes.ovpn)
