### ISSUE TITLE
Ошибка DNS. Не удаётся получить доступ к сайту

### ISSUE THREAD

**Issue by Skriptach** [zhovner/zaborona_help#141]
Недавно возникла проблема, что во время работы VPN на некоторых сайтах выдаёт две ошибки. DNS_PROBE_STARTED и затем DNS_PROBE_FINISHED_NXDOMAIN. И не удаётся получить доступ к сайту
В частности на сайте linkedin.com

Windows 7 x64 SP2
OpenVPN GUI v11.6.0.0

Ничего не менял. Ранее работало нормально

**Comment by toxi22** [comment]
Покажите, пожалуйста, скриншот трассировки в то время, когда наблюдаются проблемы с доступом.

**Comment by Skriptach** [comment]
@toxi22 Спасибо за быстрый ответ.

Какую именно трассировку имеете в виду?  Лог установки соединения или что-то другое?

![image](https://user-images.githubusercontent.com/390735/56350537-a70ab000-61d3-11e9-9e83-3e5219cbe8ea.png)

**Comment by toxi22** [comment]
Лог тоже полезный, но немного не совсем то, что нужно.
Трассировка, имеется ввиду команда:
tracert linkedin.com

Результат должен быть похожий на этот:
![2019-04-18_220941](https://user-images.githubusercontent.com/4610098/56385060-b7984600-6226-11e9-9297-b9875e896e0e.png)

**Comment by Skriptach** [comment]
Хм. Странно. Отличается только на роутере

Без VPN
![image](https://user-images.githubusercontent.com/390735/56387925-52e0e980-622e-11e9-83b2-7ae875d2aaa8.png)

VPN
![image](https://user-images.githubusercontent.com/390735/56387941-5c6a5180-622e-11e9-9652-7d91b35922f8.png)

**Comment by toxi22** [comment]
Маршруты одни и те же. Походу скорее всего сбой по региону и не зависит от VPN.

**Comment by Skriptach** [comment]
Но дело в том, что ошибка повторяется только при включённом VPN

**Comment by zhovner** [comment]
Не устанавливаются маршруты. Используйте актуальную версию windows.
