### ISSUE TITLE
Добавьте wf.mail.ru

### ISSUE THREAD

**Issue by goleo108** [zhovner/zaborona_help#163]
Это нужно для авторизации в игре Warface

**Comment by toxi22** [comment]
Трафик идет через Заборону, но на стороне провайдера, в Санкт-Петербурге проблемы с доступностью, потому не работает авторизация.
![2019-10-20_021504](https://user-images.githubusercontent.com/4610098/67152467-c946cd00-f2df-11e9-8e56-f8b3d654e75e.png)
![2019-10-20_021614](https://user-images.githubusercontent.com/4610098/67152468-c9df6380-f2df-11e9-8975-b38c61baa34c.png)

**Comment by goleo108** [comment]
Интересно, проблема с авторизацией исчезает если один раз через другой VPN зайти в игру и выбрать ник, после этого доступ к wf.mail.ru вообще не нужен.

**Comment by toxi22** [comment]
> Интересно, проблема с авторизацией исчезает если один раз через другой VPN зайти в игру и выбрать ник, после этого доступ к wf.mail.ru вообще не нужен.

Как вариант, может быть один из серверов Забороны забанен на сервере wf.mail.ru либо ему ограничили количество подключений.
