### ISSUE TITLE
Steam сегодня поломался o_O

### ISSUE THREAD

**Issue by goleo108** [zhovner/zaborona_help#170]
я не знал, что zaborona перенаправляет траффик через сервера Steam, но ведь конфиг не обновлялся уже 23 дней. я удивлён, что Steam не мог пораньше поломаться, но в любом случае отключение от VPN решило проблему https://steamcommunity.com/discussions/forum/7/1747892189238982771/

**Comment by toxi22** [comment]
У меня подключена Заборона и проблемы никогда не было.
Заборона не маршрутизирует трафик Стима.
Картинки не подгружались, скорее всего из-за проблем в DNS со стороны Забороны.

**Comment by goleo108** [comment]
@toxi22 спасибо, я ужасный сисадмин :D
@zhovner ты не против всем Windows пользователям предоставить кастомный DNS, например, 8.8.8.8? на Linux и BSD разница не будет заметна, потому что там OpenVPN не подменяет системную настройку DNS (что меня в начале взбесило, потому что я пользовался DNS сервером провайдера)

**Comment by toxi22** [comment]
@goleo108 все нормально) Все мы когда-то начинали свой путь с малого)
Для использования Гугловских ДНС, можно использовать 8.8.8.8 и 8.8.4.4.
Но если Ваш провайдер подменяет все запросы к DNS-серверам на свои, то Вам нужно будет прописать маршрут примерно такого содержания:
route add -net 8.8.8.8 netmask 255.255.255.255 gateway tun1
route add -net 8.8.4.4 netmask 255.255.255.255 gateway tun1
tun1 - это название сетевого интерфейса, через который подключена у Вас Заборона)
