### ISSUE TITLE
Ubuntu 18.04.04 Работают только заблокированные сайты

### ISSUE THREAD

**Issue by khmelev77** [zhovner/zaborona_help#172]
Здравствуйте, попробовал все установить как в этой теме: https://github.com/zhovner/zaborona_help/wiki/Ubuntu-Linux-16.04-LTS

Но столкнулся со следующей проблемой:
Если ставлю чекбокс "Использовать это соединение только для ресурсов этой сети", то заблокированные сайты недоступны (NET::ERR_CERT_COMMON_NAME_INVALID). 

А если не ставлю, то заблокированные сайты доступны, но при этом не работают обычные сайты (тоже ошибка на них NET::ERR_CERT_COMMON_NAME_INVALID).

**Comment by toxi22** [comment]
Доброго.
А ДНС правильные прописаны?
Если в обоих случаях выдается ошибка "NET::ERR_CERT_COMMON_NAME_INVALID", значит ВПН не подтянул маршруты с сервера

**Comment by khmelev77** [comment]
На http://dns-test.zaborona/ (DNS_PROBE_FINISHED_NXDOMAIN) и https://ip.mail.ru/ не заходит. (NET::ERR_CERT_COMMON_NAME_INVALID)

Вот мой список роутов
<pre>Таблица маршутизации ядра протокола IP
Destination Gateway Genmask Flags Metric Ref Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp2s0
5.45.192.0      192.168.228.1   255.255.192.0   UG    50     0        0 tun0
5.61.16.0       192.168.228.1   255.255.248.0   UG    50     0        0 tun0
5.61.232.0      192.168.228.1   255.255.248.0   UG    50     0        0 tun0
5.255.192.0     192.168.228.1   255.255.192.0   UG    50     0        0 tun0
37.9.64.0       192.168.228.1   255.255.192.0   UG    50     0        0 tun0
37.140.128.0    192.168.228.1   255.255.192.0   UG    50     0        0 tun0
50.117.0.0      192.168.228.1   255.255.255.224 UG    50     0        0 tun0
70.ip-51-254-20 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
ec2-52-28-234-1 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
62.213.108.142  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
ordns.he.net    192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
77.73.68.230    _gateway        255.255.255.255 UGH   100    0        0 enp2s0
77.74.179.130   192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
77.75.152.0     192.168.228.1   255.255.248.0   UG    50     0        0 tun0
77.88.0.0       192.168.228.1   255.255.192.0   UG    50     0        0 tun0
dns.yandex.ru   192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
79.137.157.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
79.137.183.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
front-farm-http 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
tickets.nashest 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
84.201.128.0    192.168.228.1   255.255.192.0   UG    50     0        0 tun0
84.201.148.246  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
85.192.48.0     192.168.228.1   255.255.248.0   UG    50     0        0 tun0
87.240.128.0    192.168.228.1   255.255.192.0   UG    50     0        0 tun0
87.250.224.0    192.168.228.1   255.255.224.0   UG    50     0        0 tun0
cryprox.yandex. 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
88.210.0.0      192.168.228.1   255.255.192.0   UG    50     0        0 tun0
88.217.190.96   192.168.228.1   255.255.255.224 UG    50     0        0 tun0
89.20.144.0     192.168.228.1   255.255.248.0   UG    50     0        0 tun0
89.222.152.0    192.168.228.1   255.255.248.0   UG    50     0        0 tun0
91.200.28.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
wmid.com        192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
91.227.52.0     192.168.228.1   255.255.254.0   UG    50     0        0 tun0
92.53.124.104   192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
93.158.128.0    192.168.228.1   255.255.192.0   UG    50     0        0 tun0
93.159.230.60   192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
93.186.224.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
94.100.176.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
94.143.52.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
95.108.128.0    192.168.228.1   255.255.128.0   UG    50     0        0 tun0
95.142.192.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
95.163.32.0     192.168.228.1   255.255.224.0   UG    50     0        0 tun0
95.163.144.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
95.163.248.0    192.168.228.1   255.255.248.0   UG    50     0        0 tun0
95.213.0.0      192.168.228.1   255.255.192.0   UG    50     0        0 tun0
100.43.64.0     192.168.228.1   255.255.224.0   UG    50     0        0 tun0
104.24.104.202  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
104.24.105.202  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
109.235.160.0   192.168.228.1   255.255.248.0   UG    50     0        0 tun0
128.140.168.0   192.168.228.1   255.255.248.0   UG    50     0        0 tun0
130.193.32.0    192.168.228.1   255.255.224.0   UG    50     0        0 tun0
141.8.128.0     192.168.228.1   255.255.192.0   UG    50     0        0 tun0
188.ip-145-239- 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
149.5.244.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
182.ip-151-80-1 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
154.47.0.0      192.168.228.1   255.255.0.0     UG    50     0        0 tun0
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 enp2s0
178.22.88.0     192.168.228.1   255.255.248.0   UG    50     0        0 tun0
178.154.128.0   192.168.228.1   255.255.128.0   UG    50     0        0 tun0
nm-g.nichost.ru 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
178.237.16.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
178.248.232.60  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
178.248.233.26  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
178.248.233.32  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
178.248.234.60  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
185.5.136.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.6.244.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.16.148.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.16.244.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.29.130.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
185.30.176.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.32.185.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
185.32.186.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
185.32.248.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.71.76.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
185.76.252.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
ddos-guard.net  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
188.93.56.0     192.168.228.1   255.255.248.0   UG    50     0        0 tun0
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp2s0
_gateway        0.0.0.0         255.255.255.255 UH    100    0        0 enp2s0
192.168.228.0   0.0.0.0         255.255.252.0   U     50     0        0 tun0
193.0.170.0     192.168.228.1   255.255.254.0   UG    50     0        0 tun0
193.84.255.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
194.88.208.0    192.168.228.1   255.255.254.0   UG    50     0        0 tun0
194.186.63.0    192.168.228.1   255.255.255.0   UG    50     0        0 tun0
195.93.247.69   192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
195.93.247.154  192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
195.177.205.0   192.168.228.1   255.255.255.0   UG    50     0        0 tun0
195.211.20.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
195.211.128.0   192.168.228.1   255.255.252.0   UG    50     0        0 tun0
195.218.168.0   192.168.228.1   255.255.255.0   UG    50     0        0 tun0
195.218.190.0   192.168.228.1   255.255.254.0   UG    50     0        0 tun0
199.21.96.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
199.36.240.0    192.168.228.1   255.255.252.0   UG    50     0        0 tun0
208.87.92.0     192.168.228.1   255.255.252.0   UG    50     0        0 tun0
212.5.110.40    192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
212.118.32.0    192.168.228.1   255.255.224.0   UG    50     0        0 tun0
213.180.192.0   192.168.228.1   255.255.224.0   UG    50     0        0 tun0
217.20.144.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
217.69.128.0    192.168.228.1   255.255.240.0   UG    50     0        0 tun0
61.ip-217-182-7 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
ip141.ip-217-18 192.168.228.1   255.255.255.255 UGH   50     0        0 tun0
</pre>

**Comment by khmelev77** [comment]
Вот еще скриншоты настроек VPN:
https://imgur.com/a/ouJbjxW

**Comment by toxi22** [comment]
Маршруты есть. У вас на основном сетевом интерфейсе IPv6 отключен или влючен?

**Comment by khmelev77** [comment]
А как это правильно проверить можно?
Вот попробовал так, может это о чем-то поможет (скрин):
https://imgur.com/a/EM8ETQn

**Comment by khmelev77** [comment]
Может проблема с dns? Я не могу зайти на http://dns-test.zaborona вне зависимости от того, стоит у меня чебокс "Использовать это соединение только для ресурсов этой сети" или не стоит.

**Comment by khmelev77** [comment]
Попробовал вбить DNS вручную, не помогло https://imgur.com/a/H3cpKeO

**Comment by toxi22** [comment]
> Попробовал вбить DNS вручную, не помогло https://imgur.com/a/H3cpKeO
> И еще пробовал конфигурационный файл без ipv6, точно такая же проблема.

Пробовали прописывать эти же ДНС, только не на сетевом интерфейсе Забороны, а на основном рабочем Интерфейсе?

**Comment by toxi22** [comment]
> > Попробовал вбить DNS вручную, не помогло https://imgur.com/a/H3cpKeO
> > И еще пробовал конфигурационный файл без ipv6, точно такая же проблема.
> 
> Пробовали прописывать эти же ДНС, только не на сетевом интерфейсе Забороны, а на основном рабочем Интерфейсе?

И попробуйте на основном интерфейсе, на закладке IPv6, поставить пункт "Выключено"

**Comment by khmelev77** [comment]
Попробовал, все равно проблема остаётся. Единственное что влияет, так это убирание чекбокса с "Исп. это соединение только для рес этой сети", но тогда доступны только заблок. сайты.

**Comment by khmelev77** [comment]
Вот пробовал пинговать:
1) (стоит галочка Исп. это соединение только для рес. этой сети):
**VK** (вместо вк перенаправляет на страницу с информацией о заблокированном сайте, которую возвращает мой провайдер. VPN ведет себя так, будто вообще не включен, такие же результаты получаю, когда пингуюсь без включенного VPN.)

<pre>PING vk.com (77.120.3.141) 56(84) bytes of data.
64 bytes from stub.volia.net (77.120.3.141): icmp_seq=1 ttl=128 time=13.3 ms
64 bytes from stub.volia.net (77.120.3.141): icmp_seq=2 ttl=128 time=13.1 ms
64 bytes from stub.volia.net (77.120.3.141): icmp_seq=3 ttl=128 time=12.9 ms
</pre>

**Google**
<pre>64 bytes from waw02s13-in-f14.1e100.net (172.217.16.14): icmp_seq=1 ttl=128 time=23.8 ms
64 bytes from waw02s13-in-f14.1e100.net (172.217.16.14): icmp_seq=2 ttl=128 time=24.0 ms</pre> 

2) Не стоит галочка:
**VK** (вроде все ок, никуда не перенаправляет, вк работает)
<pre>PING vk.com (87.240.139.194) 56(84) bytes of data.
64 bytes from srv194-139-240-87.vk.com (87.240.139.194): icmp_seq=1 ttl=57 time=85.6 ms
64 bytes from srv194-139-240-87.vk.com (87.240.139.194): icmp_seq=2 ttl=57 time=65.0 ms
64 bytes from srv194-139-240-87.vk.com (87.240.139.194): icmp_seq=3 ttl=57 time=62.0 ms
</pre>

**Google** (выводит одну строчку и на этом все)
<pre>PING google.com(lk-in-x66.1e100.net (2a00:1450:4010:c09::66)) 56 data bytes
</pre>

**Comment by khmelev77** [comment]
Может есть ещё какие-то способы решить эту проблему?

**Comment by khmelev77** [comment]
Проблема была в провайдере, тот подменял ответы, решается с помощью установки dns на основном интерфейсе (поставил 1.1.1.1, но можно и от днс от гугл например).
