### ISSUE TITLE
kinopoisk.ru - 403 Forbidden

### ISSUE THREAD

**Issue by TestUser013** [zhovner/zaborona_help#175]
Здравствуйте, с недавнего времени при попытке открыть kinopoisk.ru [213.180.193.105] отображается страница с надписью 403 Forbidden nginx. Несколько недель назад сайт прекрасно открывался.

**Comment by toxi22** [comment]
Доброго.
Сервера Забороны попали в бан-лист kinopoisk.ru
Вы можете использовать тестовый 8 сервер, если Вам нужен сайт kinopoisk.ru
На этом сервере он все еще работает, но как долго будет рабочим - не могу сказать.

**Comment by TestUser013** [comment]
Напишу письмо к ним в поддержку, надеюсь что-то ответят.

**Comment by TestUser013** [comment]
Ответили :(

> Здравствуйте, ****!
> 
> Дело в том, что мы не поддерживаем работу сервиса при включенном VPN. Онлайн-кинотеатр КиноПоиска официально работает только на территории России, Казахстана и Беларуси.

**Comment by TestUser013** [comment]
Представитель поддержки ответил позитивно. У меня кинопоиск начал рабоать без изминения настроек (я пользуюсь pac файлом). 
> С нашей стороны блокировки не было. Пожалуйста, попробуйте воспользоваться 8-ым тестовым сервером, как порекомендовал вам сотрудник сайта zaborona.help. 
> Если через него тоже не получится воспользоваться сервисом, напишите нам. Попробуем что-нибудь сделать.
