### ISSUE TITLE
Просьба добавить заблокированные сайты

### ISSUE THREAD

**Issue by evgen--** [zhovner/zaborona_help#179]
Ссылка: http://rusvesna.su/
IP: 104.20.74.219 | 104.20.73.219 | 172.67.3.106

Ссылка: http://ukraina.ru/
IP: 178.248.233.60

Ссылка: http://tass.ru/
IP: 82.202.190.72

**Comment by Aksi0** [comment]
На каком провайдере они заблокированы?

**Comment by toxi22** [comment]
Сайты должна работать без проблем на конфигурации zaborona-help_maxroutes.ovpn
