### ISSUE TITLE
Проблемы с доступностью сайтов

### ISSUE THREAD

**Issue by TrueXakeP** [zhovner/zaborona_help#185]
Есть проблема с доступностью (timeout) сайтов из этого списка (кроме drweb.ru) и через vpn (на обоих портах 1194 и 1196), и через socks5:
https://github.com/zhovner/zaborona_help/blob/e09acf01f30c6361e2c3ddb90375ca60846fbd7b/config/openvpn/ccd/DEFAULT#L114-L115
Главное, что на IP из этой сети находится хабр `nslookup habr.com` => `Address:  178.248.237.68` и он тоже становиться недоступен при использовании zaborona.help. Через vpn — через раз.

Использую pull-filter ignore для обхода проблемы и решил о ней сообщить.

**Comment by toxi22** [comment]
Спасибо за информацию. Решим, как будет лучше исправить этот момент.

**Comment by toxi22** [comment]
Проверьте, пожалуйста, работает ли хабр без проблем с включенной Забороной и без использования pull-filter ignore

**Comment by TrueXakeP** [comment]
Да, теперь хабр работает напрямую.

**Comment by TrueXakeP** [comment]
Ситуация повторяется с сайтами `srv.habr.com` => `178.248.233.33` (с него тянутся фреймы в статьи) и `linux.org.ru` => `178.248.233.6`.
Проблемы теже обе — периодическая недоступность сайтов в этой сети и проход этих двух разрешенных через vpn

**Comment by TrueXakeP** [comment]
Ах да, `qna.habr.com` => `178.248.233.33` там же.

**Comment by toxi22** [comment]
Хорошо, проверим.

**Comment by TrueXakeP** [comment]
И снова здравствуйте, как говорится...
То, что маршрут к, вроде бы, не заблокированному OpenDNS (`208.67.220.220`/`208.67.222.222`) проложен через VPN так и задумано? (довольно неожиданно). В общем и он теперь не отвечает.

**Comment by toxi22** [comment]
> И снова здравствуйте, как говорится... То, что маршрут к, вроде бы, не заблокированному OpenDNS (`208.67.220.220`/`208.67.222.222`) проложен через VPN так и задумано? (довольно неожиданно). В общем и он теперь не отвечает.

Здравствуйте.
Да, так задумано.
Когда VPN поднят, то по факту запросы не доходят до OpenDNS, а заворачиваются на CloudFlare на самом сервере и идут через CF

**Comment by toxi22** [comment]
> И снова здравствуйте, как говорится...
> То, что маршрут к, вроде бы, не заблокированному OpenDNS (`208.67.220.220`/`208.67.222.222`) проложен через VPN так и задумано? (довольно неожиданно). В общем и он теперь не отвечает.

Переподключитесь и проверьте, пожалуйста, корректно ли открываются сайты.

**Comment by TrueXakeP** [comment]
Так да — сайты открываются. Но в данном случае мне важнее, чтобы OpenDNS шел напрямую (ну да "pull-filter ignore").
Мне просто любопытно почему было принято такое решение? Почему перехват? Почему именно OpenDNS? Почему не, допустим, какой-то собственный или тот же уже все равно заблокированный Яндекс? У меня вот прекрасно работает ваш же (ну не ваш лично) совет использовать DNS Яндекса для доменов Яндекса (да и остальных заблокированных ресурсов), чтобы yandex.ua не прыгал.

**Comment by toxi22** [comment]
> Так да — теперь сайты открываются. Но в данном случае мне важнее, чтобы OpenDNS шел напрямую (ну да "pull-filter ignore"). Мне просто любопытно почему было принято такое решение? Почему перехват? Почему именно OpenDNS? Почему не, допустим, какой-то собственный или тот же уже все равно заблокированный Яндекс? У меня вот прекрасно работает ваш же (ну не ваш лично) совет использовать DNS Яндекса для доменов Яндекса (да и остальных заблокированных ресурсов), чтобы yandex.ua не прыгал.

С Яндекс.ДНС были проблемы и смена ДНС на OpenDNS помогла решить проблему с доступностью сайтов.
На данный момент вернули Яндекс.ДНС, который выдается пользователям, но на сервере все равно идет перехват ДНС запросов для того, чтобы отдавать правильные МСК IP-адреса серверов Яндекса и Мейл.ру (чтобы запросы не шли на Украинские сервера, которые заблокированы).
OpenDNS используется очень маленьким числом пользователей и приняли решение использовать именно его.
Да, можно использовать локальный ДНС сервер и отдавать его пользователям. Над этим вариантом думаем.

**Comment by TrueXakeP** [comment]
А перехватывать Яндекс днс, и заворачивать его на DoH CF целиком, как 
сейчас с OpenDNS? С этим проблемы и были? Простите за назойливость :)

Roman ***@***.***> 19 декабря 2021 г. 15:30:50 написал:

**Comment by toxi22** [comment]
> А перехватывать Яндекс днс, и заворачивать его на DoH CF целиком, как сейчас с OpenDNS? С этим проблемы и были? 

Попробуем так сделать. Раньше не был настроен CloudFlare DOH на сервере)

**Comment by TrueXakeP** [comment]
Ясно, спасибо.
Удачи вам! :)
Все прекрасно, все работает. :)
Спасибо за сервис - полезный.

Roman ***@***.***> 19 декабря 2021 г. 23:44:41 написал:
