### ISSUE TITLE
Произвольная перезагрузка Asus RT-AX55 с клиентом OpenVPN

### ISSUE THREAD

**Issue by DennisLypovetsky** [zhovner/zaborona_help#195]
Купил новый роутер `Asus RT-AX55`. Настроил [по инструкции для AsusWRT](https://github.com/zhovner/zaborona_help/wiki/AsusWRT).

Всё работает, но иногда, 1–4 раза в день происходит произвольная перезагрузка роутера: сначала пропадает интернет, потом перезагружается роутер и всё снова в порядке.

Закономерности в перезагрузках нет: неважно кол-во подключённых устройств или время дня.

Я попробовал на пару дней отключить OpenVPN и это помогло! Роутер перестал перезагружаться. Выходит, дело в настройках связанных с VPN?

Подскажите, пожалуйста, что делать, чтобы роутер работал с Zaborona OpenVPN? Роутер Asus выбрал из-за самой простой инструкции на сайте, но ещё не прошли 14 дней, могу вернуть и взять другую модель. Или перепрошить этот на кастомную прошивку.

`Версия прошивки: 3.0.0.4.386_42844` (Последняя)

**Comment by toxi22** [comment]
Добрый день.
Если перепрошьете роутер на кастом, то вероятнее всего потеряете гарантию (нужно посмотреть условия гарантии). Прошивка на кастом, вероятнее всего, сможет решить проблему, но смотрите сами, как лучше Вам поступить.
Наиболее вероятная причина перезагрузок - утечка памяти (нехватка ресурсов роутера для корректной работы OpenVPN)

**Comment by DennisLypovetsky** [comment]
![ОЗУ роутера под обычной нагрузкой и после перезагрузки](https://user-images.githubusercontent.com/24877432/128611068-63c00063-3f2a-4bab-8a5a-898db9467040.png)
Ресурсы роутера до и после перезагрузки.

А какая кастомная прошивка справится лучше с утечкой памяти из-за OpenVPN? Проще говоря, что лучше поставить если придётся? Или может быть есть более подходящие для OpenVPN роутеры? Может, не Asus.

Я понимаю, что вы, конечно, не можете протестировать все модели. Я очень благодарен вам за zaborona.help! Но, возможно, вы могли бы подсказать, что выбрать. Мой выбор базировался на простоте инструкции. А конкретную модель я выбрал [просто из тех, что были сверху в hotline](https://hotline.ua/computer/besprovodnoe-oborudovanie/?q=%D1%80%D0%BE%D1%83%D1%82%D0%B5%D1%80+asus).

**Comment by toxi22** [comment]
Если на альтернативную прошивку шить, то в прошивке может быть исправлены проблемы в работе в openvpn.
Я прошивал RT-N66U на прошивку Asus-Merlin. OpenVPN работает на этой прошивке хорошо, только есть минус, что нельзя гостевые сети добавлять, потому что роутер начинает неадекватно себя вести и пропадает интернет и локальная сеть.
Так же прошивал роутер RT-N15U на прошивку Tomato с поддержкой VPN. В этом роутере мало оперативной памяти, поэтому пришлось выбрать самую минимальную конфигурацию для Tomato.

Для роутеров, типа ТП-Линк и Д-Линк, прошивал OpenWRT и DDWRT, но не все модели поддерживают дополнительные модули, в которые входит openvpn из-за малого объема озу и места на флешке.
Список моделей, которые поддерживает openwrt: https://openwrt.org/toh/views/toh_fwdownload

Рекомендуют еще Зиксель Кинетик/Гига/Ультра. OpenVPN так же ставится из дополнительных пакетов.

**Comment by DennisLypovetsky** [comment]
Большое спасибо за ответ! Теперь я примерно знаю куда двигаться. 

Я попробую сперва найти решение с этим роутером. Отпишусь, если получится и если нет.

**Comment by DennisLypovetsky** [comment]
Я тестировал роутер у себя и в другой квартире с другим провайдером и пришёл. Менял настройки, кол-во подключений, нагрузку… Всё равно, роутер именно у меня произвольно перезагружался. В другой квартире проблем не было. Так что я пожал плечами и просто сменил модель на RT-AC51U. Роутер по цифрами слабее, но с ним проблем не возникло.

Предположение: проблема в провайдере и способе подключения. У меня интернет в роутер поставляется через модем. Провайдер использует кабель с интернетом + ТВ (не знаю точно, как называется этот тип подключения). Возможно, это создаёт дополнительную нагрузку или что-то в этом роде.
