### ISSUE TITLE
добавьте .pac для файерфокса и иже с ним...

### ISSUE THREAD

**Issue by admzzz** [zhovner/zaborona_help#203]
по аналогии с https://antizapret.prostovpn.org/proxy.pac

**Comment by toxi22** [comment]
Добрый день.
Есть такой файл: https://zaborona.help/proxy.pac
Но он давно не обновлялся. Поэтому, если Вы проверите его работу и отпишитесь, будет хорошо.

**Comment by admzzz** [comment]
спасибо за ответ, проверить, увы, не могу из-за нынешней геолокации ;-)
