### ISSUE TITLE
Конфликтный роут на srv8

### ISSUE THREAD

**Issue by kilroy98** [zhovner/zaborona_help#204]
Хоть сервер и тестовый, но может можно поправить это? Или это не является проблемой? При подключении через обычный конфиг, данной ошибки нет.

>Ignore conflicted routing rule: 185.5.136.0 255.255.252.0

**Comment by toxi22** [comment]
Добрый день.
Исправим. Спасибо за информацию.

**Comment by kilroy98** [comment]
И ещё чисто как хотелка (если возможно), сделать два конфига этого сервера, как сейчас с основными, обычный и _maxroutes.

**Comment by toxi22** [comment]
> И ещё чисто как хотелка (если возможно), сделать два конфига этого сервера, как сейчас с основными, обычный и _maxroutes. Или сейчас конфиг для srv8 работает как _maxroutes?

srv8 работает так же с _maxroutes. Вам нужно только изменить порт подключения на 1196

**Comment by toxi22** [comment]
> Хоть сервер и тестовый, но может можно поправить это? Или это не является проблемой? При подключении через обычный конфиг, данной ошибки нет.
> 
> > Ignore conflicted routing rule: 185.5.136.0 255.255.252.0

Ошибка конфликтного маршрута уже не должна появляться

**Comment by kilroy98** [comment]
Почему-то ошибка не ушла, к сожалению.
Dec 11 14:23:24 vpnclient4[8442]: /sbin/route add -net 185.5.136.0 netmask 255.255.252.0 gw 192.168.224.1
Dec 11 14:23:24 vpnclient4[8442]: Ignore conflicted routing rule: 185.5.136.0 255.255.252.0

**Comment by kilroy98** [comment]
Сейчас заметил, что не хочет подключаться по обычному конфигу, с изменённым конфигом на 1196 порт - проблем нету.

**Comment by toxi22** [comment]
> Сейчас заметил, что не хочет подключаться по обычному конфигу, с изменённым конфигом на 1196 порт - проблем нету.

Проверим. Спасибо за информацию.

**Comment by kilroy98** [comment]
По обычному конфигу вернулась возможность подключаться к srv8 (и возможно уже давно, но проверить решил только сейчас), но конфликтный роут никуда не делся, к сожалению.
