### ISSUE TITLE
Wrong route for linux.org.ru on mikrotik

### ISSUE THREAD

**Issue by AndriiZ** [zhovner/zaborona_help#206]
VPN: vpn.zaborona.help
Port: 1196

Route with vpn: 
![screenshot_40](https://user-images.githubusercontent.com/820269/146421985-f08b082f-695c-4597-9af5-88695b477da1.png)
Route without vpn:
![зображення](https://user-images.githubusercontent.com/820269/146422076-84c8c08c-9492-43a6-b896-5dead5423854.png)

**Comment by DJm00n** [comment]
Seeing same issue on my side
```
djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
 1  192.168.88.1 (192.168.88.1)  2.033 ms  186.275 ms  1.326 ms
 2  192.168.224.1 (192.168.224.1)  44.679 ms  308.996 ms  422.961 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  *^C
```

**Comment by toxi22** [comment]
> Seeing same issue on my side
> 
> ```
> djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
> traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
>  1  192.168.88.1 (192.168.88.1)  2.033 ms  186.275 ms  1.326 ms
>  2  192.168.224.1 (192.168.224.1)  44.679 ms  308.996 ms  422.961 ms
>  3  * * *
>  4  * * *
>  5  * * *
>  6  * * *
>  7  * * *
>  8  *^C
> ```
> 
> Without zaborona
> 
> ```
> djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
> traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
>  1  192.168.88.1 (192.168.88.1)  2.083 ms  1.378 ms  1.058 ms
>  2  10.0.255.255 (10.0.255.255)  1.417 ms  2.130 ms  2.053 ms
>  3  194.33.189.15 (194.33.189.15)  8.494 ms  38.033 ms  1.865 ms
>  4  ae3-210.rt.bmb.kiv.ua.retn.net (87.245.247.158)  2.202 ms  2.400 ms  1.937 ms
>  5  ae2-6.rt.ok.msk.ru.retn.net (87.245.232.204)  22.287 ms  22.681 ms  22.424 ms
>  6  gw-xtend.retn.net (87.245.253.194)  28.853 ms  22.802 ms  22.386 ms
> ```

Hi.
Thanks for the info, we'll check it out.

**Comment by toxi22** [comment]
> Seeing same issue on my side
> 
> ```
> djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
> traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
>  1  192.168.88.1 (192.168.88.1)  2.033 ms  186.275 ms  1.326 ms
>  2  192.168.224.1 (192.168.224.1)  44.679 ms  308.996 ms  422.961 ms
>  3  * * *
>  4  * * *
>  5  * * *
>  6  * * *
>  7  * * *
>  8  *^C
> ```
> 
> Without zaborona
> 
> ```
> djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
> traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
>  1  192.168.88.1 (192.168.88.1)  2.083 ms  1.378 ms  1.058 ms
>  2  10.0.255.255 (10.0.255.255)  1.417 ms  2.130 ms  2.053 ms
>  3  194.33.189.15 (194.33.189.15)  8.494 ms  38.033 ms  1.865 ms
>  4  ae3-210.rt.bmb.kiv.ua.retn.net (87.245.247.158)  2.202 ms  2.400 ms  1.937 ms
>  5  ae2-6.rt.ok.msk.ru.retn.net (87.245.232.204)  22.287 ms  22.681 ms  22.424 ms
>  6  gw-xtend.retn.net (87.245.253.194)  28.853 ms  22.802 ms  22.386 ms
> ```

Hi!
Updated the list of sites on servers. Reconnect to the servers and check, please, if the sites open correctly

**Comment by DJm00n** [comment]
Hey @toxi22!
Working fine now on my side. Thank you!

With zaborona:
```
djm00n@MacBook-Pro:~|⇒  traceroute linux.org.ru
traceroute to linux.org.ru (178.248.233.6), 64 hops max, 52 byte packets
 1  192.168.88.1 (192.168.88.1)  20.548 ms  12.174 ms  10.119 ms
 2  192.168.224.1 (192.168.224.1)  78.898 ms  289.631 ms  67.101 ms
 3  77.73.64.1 (77.73.64.1)  70.081 ms  82.705 ms  76.342 ms
 4  bg.rnet.ru (94.242.0.1)  81.188 ms  107.974 ms  129.300 ms
 5  87.245.228.188 (87.245.228.188)  184.209 ms  184.601 ms  119.287 ms
 6  ae2-6.rt.ok.msk.ru.retn.net (87.245.232.204)  99.873 ms  116.213 ms  150.900 ms
 7  gw-xtend.retn.net (87.245.253.194)  218.005 ms  120.814 ms *
```
