### ISSUE TITLE
Pidgin не может подключиться к вк

### ISSUE THREAD

**Issue by medvedar** [zhovner/zaborona_help#21]
Привет.
Вчера (31.05) вечером пропала возможность подключаться pidgin-ом к вк. Выдает ошибку "Wrong username or password". При этом через браузер заходит нормально.

При использовании другого VPN-сервера pidgin подключается нормально.

**Comment by zhovner** [comment]
Мало информации. Уточните на какой IP адрес происходит попытка подключения. У Pidgin должен быть отладочный лог. Возможно ли что это VK.com заблокировал подключения с нашего IP из-за большого числа клиентов?

**Comment by medvedar** [comment]
tcpdump показывает `srv139-11-213-95.vk.com`
Но вот все же решилось: перелогинился в браузере, вк запросил ввести капчу. После этого и pidgin нормально подключился. Хотя вчера это на срабатывало.
