### ISSUE TITLE
Добавьте drive2.ru

### ISSUE THREAD

**Issue by Sho0terInfo** [zhovner/zaborona_help#211]
Добавьте пожалуйста в список IP drive2.ru
inetnum: 146.255.192.0 - 146.255.195.255

**Comment by toxi22** [comment]
Добрый день.
Добавили. Переподключитесь и проверьте работу.

**Comment by Sho0terInfo** [comment]
Добавил себе в конфиг забороны

# Drive2
route 146.255.192.0 255.255.252.0

Работает, спасибо!
