### ISSUE TITLE
А зачем приходит маршрут на 0.0.0.0 ?

### ISSUE THREAD

**Issue by LESHIY-ODESSA** [zhovner/zaborona_help#233]
Здравствуйте.

MikroTik RouterOS 7.2rc5
srv0.vpn.zaboronahelp.pp.ua — 1196

**А зачем приходит маршрут на 0.0.0.0 ?**

**Comment by toxi22** [comment]
Добрый день.
Возможно у Вас установлена галочка "Add Default Route", то машрут 0.0.0.0 не будет прописываться.
[скрин 1](https://prnt.sc/BXrxHlKj9pfl)
[скрин 2](https://prnt.sc/Rpr-1Jg5tehE)
