### ISSUE TITLE
Игнорирование DNS от забороны

### ISSUE THREAD

**Issue by kilroy98** [zhovner/zaborona_help#244]
Здравствуйте, а как-то можно сделать чтобы при подключении к серверам игнорировался получаемый DNS-сервер? Сейчас прилетает DNS Яндекса, из-за этого на некоторых сайтах проблема с загрузкой контента. В том же Стиме, например, отваливаются абсолютно все картинки. Как пример ещё trovo.live, часть сайта загружается, которая сидит за клаудом, весь остальной контент не загружается, потому что он пытается загрузится с серверов в РФ, которые естественно попали под блокировку.

**Comment by toxi22** [comment]
Добрый день.
Попробуйте так (пример):
```
pull-filter ignore "dhcp-option DNS 77.88.8.8"
pull-filter ignore "route 77.88.8.8"
pull-filter ignore "dhcp-option DNS 77.88.8.1"
pull-filter ignore "route 77.88.8.1"
```
Нужно прописать в конфиг-файле.

Вообще на сервере реализовано заворачивание любого ДНС-запроса, если он без шифрование, на сервера CloudFlare либо Google DNS. Вероятно, в Вашей ситуации, используются провайдерские ДНС, которые фильтруются у провайдера и отдают неверный ответ.
Это можно проверить, например, здесь: https://whoer.net/ru/dns-leak-test

**Comment by toxi22** [comment]
Постараемся решить этот вопрос с нашей стороны

**Comment by toxi22** [comment]
Дополнение:
Подтерадктировали настройки dns-резолвера на конфиге srv0.vpn.zaborona.help.
По сути nslookup видит, что ДНС от яндекса, но резолвит на правильный айпишник.
Переподключитесь и проверьте, как у Вас будет вести себя сайт в таком варианте.
Сейчас ситуация изменилась:
![2022-04-01_181353](https://user-images.githubusercontent.com/4610098/161292104-d1e00894-0098-4944-b7ac-c8eabf16748c.png)
![2022-04-01_181407](https://user-images.githubusercontent.com/4610098/161292109-dcd028e6-9a9b-4db0-81f5-0cf191dcd07c.png)

**Comment by kilroy98** [comment]
Проверил, теперь нету проблемы. Напрямую подключить кабель в ПК не могу сейчас, дабы проверить через командную строку, поэтому проверяю опять же через админку роутера. Теперь при подключении к забороне видит DNS Cloudflare и на том сайте мне опять же выдаёт что обнаружена утечка и выдаёт 5 адресов Cloudflare, Германия. 

> Server:    1.0.0.1
> Address 1: 1.0.0.1 one.one.one.one
> 
> Name:      headicon.trovo.live
> Address 1: 101.33.10.52
> Address 2: 101.33.11.29
> Address 3: 101.33.11.110
> Address 4: 101.33.11.88
> Address 5: 101.33.11.48
> Address 6: 101.33.11.45

Стоит ожидать это исправление для остальных серверов? У меня пока ещё каким-то чудом подключается по конфигу zaborona-help и zaborona-help_maxroutes.

**Comment by toxi22** [comment]
Да, на остальных исправим тоже

**Comment by kilroy98** [comment]
Что-то у меня осталась проблема на конфиге, который на сервера в Питере направлен, как будто фикс не применился там. Плюс при подключении к этому конфигу (_maxroutes) теперь появились конфликтные роуты
>Ignore conflicted routing rule: 185.65.148.0 255.255.252.0
>Ignore conflicted routing rule: 193.84.85.0 255.255.255.0
>Ignore conflicted routing rule: 193.84.88.0 255.255.255.0
>Ignore conflicted routing rule: 193.84.90.0 255.255.255.0

и такая ошибка ещё проскакивает.
>ERROR: Linux route add command failed: external program exited with error status: 1

Это всё если подключатся к VPN на роутере.

На винде же, при подключении через OpenVPN GUI нету ничего о конфликтных роутах, зато есть вот такие сообщения
>ROUTE: route addition failed using service: Ïàðàìåòð çàäàí íåâåðíî.   [status=87 if_index=16]
>ROUTE: route addition failed using service: Ïàðàìåòð çàäàí íåâåðíî.   [status=87 if_index=16]
>ROUTE: route addition failed using service: Ïàðàìåòð çàäàí íåâåðíî.   [status=87 if_index=16]
>ROUTE: route addition failed using service: Ýòîò îáúåêò óæå ñóùåñòâóåò.   [status=5010 if_index=16]
>ROUTE: route addition failed using service: Ýòîò îáúåêò óæå ñóùåñòâóåò.   [status=5010 if_index=16]
>ROUTE: route addition failed using service: Ýòîò îáúåêò óæå ñóùåñòâóåò.   [status=5010 if_index=16]
>ROUTE: route addition failed using service: Ýòîò îáúåêò óæå ñóùåñòâóåò.   [status=5010 if_index=16]

И такие же ошибки есть и на srv0, что с _maxroutes, что без.

**Comment by toxi22** [comment]
Ошибку исправили. Дубликаты маршрутов тоже обнаружили и их убрали.
На роутере, подключение, уже должно работать без проблем.

**Comment by kilroy98** [comment]
Спасибо, теперь нету проблем с подключением. Но вот фикс DNS, который вы делали для srv0, видимо так и не добрался до серверов в СПб :( Всё также nslookup на `headicon.trovo.live` выдаёт такой результат
```
Server:    77.88.8.8
Address 1: 77.88.8.8 dns.yandex.ru

Name:      headicon.trovo.live
Address 1: 46.46.151.6
Address 2: 46.46.151.2
Address 3: 46.46.151.44
Address 4: 46.46.151.43
Address 5: 46.46.151.34
```

**Comment by toxi22** [comment]
Спасибо за информацию. Проверим, почему на сервера в СПБ не применился фикс

**Comment by kilroy98** [comment]
Подключался ко всем серверам, которые мне доступны (srv1, 2, 5 и 6), нигде так и нету фикса. Думал может чего с конфигом не так, но сравнил с конфигом от srv0 - всё 1 в 1 (ну кроме адреса естественно).

**Comment by toxi22** [comment]
Там используется CloudFlare, но он идет на сервера в РФ, а не на Американские сервера. В РФ тоже есть сервера CF и клиент видит, что до них ближе. Рассмотрим другой вариант DOH, если не удастся решить вопрос с официальным CloudFlare клиентом

**Comment by kilroy98** [comment]
Я пока решил вопрос так, добавил в конфиг:
```
dhcp-option DNS 1.1.1.1
dhcp-option DNS 1.0.0.1
```
Внутри роутера нашёл где появляются файлы OpenVPN, после подключения к серверу, в resolv.conf всё равно фигурируют DNS Яндекса, но перед ними теперь появляются DNS Cloudflare. Адреса получаются нормально теперь, видимо DNS Cloudflare используются в приоритете в таком варианте.
Я бы забил на всё это, но хочется чтобы был доступ к музыке в ВК. Плюс обнаружился неприятный минус, что пропадает доступ к некоторым сайтам (обнаружился пока только один - tax.gov.ua), домен просто не резолвится. (Cloudflare тоже попал под блокировку что-ли? Или в РФ они на чужих мощностях и на чужих IP сидят?)

**Comment by toxi22** [comment]
> (Cloudflare тоже попал под блокировку что-ли? Или в РФ они на чужих мощностях и на чужих IP сидят?)

Проверим.
Насколько было замечено, то некоторые провайдеры блокируют по IP адресам, не разбираясь, это айпишник сервера или прокси-сервера, типа CloudFlare.
