### ISSUE TITLE
Можно ли добавить доступ к серверу GTA V RP

### ISSUE THREAD

**Issue by AdnanTim** [zhovner/zaborona_help#251]
IP сервера s1.arizona-v.com:22005

**Comment by toxi22** [comment]
К сожалению, игровые сервера не можем добавить, так как это создаст нагрузку на канал и на сервер в целом.
Можете рассмотреть вариант заказа и самостоятельной оплаты виртуального сервера, например, в Европе, чтобы использовать его для доступа к игровым серверам в РФ.
Если нужна будет помощь с настройкой, обращайтесь.
