### ISSUE TITLE
BGP маршруты

### ISSUE THREAD

**Issue by dronmaxman** [zhovner/zaborona_help#255]
Приветствую. 

Есть в планах реализовать отдачу маршрутов по BGP ?

**Comment by toxi22** [comment]
Здравствуйте.
Есть. Даже конфигурация на стороне сервера была готова, но пока не протестировано.

**Comment by A-I-Demidov** [comment]
> Приветствую.
> 
> Есть в планах реализовать отдачу маршрутов по BGP ?

Это есть тут https://antifilter.network

Ребята помогают обходить российские блокировки ну и заодно и наш лист подтянули.

**Comment by dronmaxman** [comment]
> > Приветствую.
> > Есть в планах реализовать отдачу маршрутов по BGP ?
> 
> Это есть тут https://antifilter.network
> 
> Ребята помогают обходить российские блокировки ну и заодно и наш лист подтянули.

Я нахожусь в Украине. Зачем мне список адресов заблокированных в РФ? В моей стране они не заблокированы.

**Comment by A-I-Demidov** [comment]
> > > Приветствую.
> > > Есть в планах реализовать отдачу маршрутов по BGP ?
> > 
> > 
> > Это есть тут https://antifilter.network
> > Ребята помогают обходить российские блокировки ну и заодно и наш лист подтянули.
> 
> Я нахожусь в Украине. Зачем мне список адресов заблокированных в РФ? В моей стране они не заблокированы.

Прочитайте внимательно что я написал и что предлагает ресурс.
![image](https://user-images.githubusercontent.com/107837323/193788491-5bf59111-5bbc-452a-8f8a-171df743ae66.png)

**Comment by A-I-Demidov** [comment]
> Спасибо, настроил, работает. Правда этот список не особо помогает т.к. многие площадки в РФ просто заблокировали доступ из Украины. Остановился на полном списке BGP "адреса российских сетей сегмента"

Я сделал так же.

Правда теперь думаю, как сделать так чтобы по время закачки торрента отключать обход, так как вместо гигабита получаю ограничения ширины канала VPN )

**Comment by dronmaxman** [comment]
Проблема решена с помощью https://antifilter.network/
