### ISSUE TITLE
Не работает ни один из конфигов на роутере Keenetic Viva

### ISSUE THREAD

**Issue by xScr3amox** [zhovner/zaborona_help#257]
Настроил всё по инструкции для нового дизайна админ панели, но запускаться ни один из конфигов не хочет. Ниже фото настроек.

<img width="608" alt="Снимок экрана 2022-04-15 в 22 16 58" src="https://user-images.githubusercontent.com/29512911/163623207-386ec205-36fe-4383-b687-033c427c147c.png">

<img width="608" alt="Снимок экрана 2022-04-15 в 22 18 24" src="https://user-images.githubusercontent.com/29512911/163623047-62ed19d8-113a-4735-b7d3-56c78d156b64.png">
<img width="608" alt="Снимок экрана 2022-04-15 в 22 17 24" src="https://user-images.githubusercontent.com/29512911/163623075-d20360bb-1733-4950-806d-c31341cee70c.png">
<img width="1209" alt="Снимок экрана 2022-04-15 в 22 18 54" src="https://user-images.githubusercontent.com/29512911/163623090-30ad4882-9cdd-4543-99e2-d1cb39dcb28b.png">

Подскажите что сделал не так, через опенвпн клиент те же настройки работают.

**Comment by toxi22** [comment]
Добрый день.
Вам нужно убрать из файла строку:
`setenv opt block-outside-dns`
Чтобы все заработало.
Вот пример конфига, который работает на Кинетике:
[srv0.zaborona-help-UDP-no-encryption_maxroutes.txt](https://zaborona.help/openvpn-client-config/txt-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.txt)

**Comment by xScr3amox** [comment]
> Добрый день. Вам нужно убрать из конфига строку: `setenv opt block-outside-dns` чтобы все заработало. Вот пример конфига, который работает на Кинетике: [srv0.zaborona-help-UDP-no-encryption_maxroutes.txt](https://zaborona.help/openvpn-client-config/txt-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.txt)

Этот конфиг не заработал, но тот что был после удаления setenv opt block-outside-dns заработал сразу. Спасибо большущее вам)
