### ISSUE TITLE
4pda.to

### ISSUE THREAD

**Issue by luxeceiling** [zhovner/zaborona_help#262]
Доброго времени, добавьте  пожалуйста 4pda.to
За ранее благодарен

**Comment by toxi22** [comment]
> Доброго времени, добавьте пожалуйста 4pda.to За ранее благодарен

Добавили новые айпишники для сайта. Проверьте, пожалуйста, как работает сайт

**Comment by luxeceiling** [comment]
Добрый день все так же, подключение remote socks.zaboronahelp.pp.ua, через оперу с впн работает

**Comment by luxeceiling** [comment]
Может надо обновить сертификаты?

**Comment by toxi22** [comment]
> Добрый день все так же, подключение remote socks.zaboronahelp.pp.ua, через оперу с впн работает

Укажите порт (при условии, что Вы подключаетесь через openvpn, а не через прокси): 
remote socks.zaboronahelp.pp.ua 1196

На порту 1194 не будет работать расширенный список сайтов.

Список сайтов для прокси пока не обновлялся

**Comment by luxeceiling** [comment]
Подключаюсь через openvpn роутер кинетик, инструкцию брал с Вашего сайта, подскажите пожалуйста какие еще есть варианты настройки на этом роутере и где их можно посмотреть.

**Comment by toxi22** [comment]
> Подключаюсь через openvpn роутер кинетик, инструкцию брал с Вашего сайта, подскажите пожалуйста какие еще есть варианты настройки на этом роутере и где их можно посмотреть.

Изменить адрес с remote socks.zaboronahelp.pp.ua на адрес remote socks.zaboronahelp.pp.ua 1196 и переподключиться и все должно заработать

**Comment by toxi22** [comment]
> > Подключаюсь через openvpn роутер кинетик, инструкцию брал с Вашего сайта, подскажите пожалуйста какие еще есть варианты настройки на этом роутере и где их можно посмотреть.
> 
> Изменить адрес с `remote socks.zaboronahelp.pp.ua` на адрес `remote socks.zaboronahelp.pp.ua 1196` и переподключиться и все должно заработать

**Comment by toxi22** [comment]
> nobind
> client
> remote socks.zaboronahelp.pp.ua 1196
> remote-cert-tls server
> cipher AES-128-CBC
> setenv opt ncp-ciphers AES-128-GCM
> #setenv opt block-outside-dns
> dev tun
> proto tcp
> ниже идет сертификаты,
> может что еще надо поправить?

Попробуйте указать вот так:
setenv opt ncp-ciphers AES-128-GCM:AES-128-CBC:AES-256-GCM:AES-256-CBC

**Comment by luxeceiling** [comment]
К сожаленью не помогает, на 1196 вообще ничего не работает, на 1194 все открывается, кроме 4pda,

**Comment by toxi22** [comment]
> К сожаленью не помогает, на 1196 вообще ничего не работает, на 1194 все открывается, кроме 4pda,

На порту 1194 очень ограниченный список сайтов (Мейл.ру, ВК, ОК, Др. Веб, Касперский и все), потому что на старых устройствах и прошивках не будет работать список, который превышает 100 маршрутов.
На порту 1196 огромный список сайтов, в том числе и 4pda.

Вы запускаете опенвпн на роутере или на ПК?
Если на роутере, то подскажите, какой у Вас роутер?

**Comment by luxeceiling** [comment]
Добрый день keenetik ultra. настроен на нем OpenVPN. по инструкции с сайта заборна, если я меняю порт на 1196, у меня вообще ничего не работает

**Comment by luxeceiling** [comment]
Вот что у меня настроено 
nobind
client
remote socks.zaboronahelp.pp.ua 1194
remote-cert-tls server
cipher AES-128-CBC
setenv opt ncp-ciphers AES-128-GCM:AES-128-CBC:AES-256-GCM:AES-256-CBC
#setenv opt block-outside-dns
dev tun
proto tcp

**Comment by toxi22** [comment]
> Добрый день keenetik ultra. настроен на нем OpenVPN. по инструкции с сайта заборна, если я меняю порт на 1196, у меня вообще ничего не работает

Попробуйте подождать около 1 минуты, чтобы все параметры загрузились.


> remote socks.zaboronahelp.pp.ua 1194

Вместо `remote socks.zaboronahelp.pp.ua 1194` лучше пропишите адрес `remote srv0.vpn.zaboronahelp.pp.ua 1196`.
Так как на адрес `srv0.vpn.zaboronahelp.pp.ua` добавлено несколько серверов для распределения нагрузки и увеличения отказа в работе (если один из серверов вдруг перестанет работать, то роутер автоматически переключится на другой сервер)

Еще будет хорошо, если Вы сможете прикрепить лог-файл, чтобы можно было провести диагностику, почему у Вас не подключается роутер к порту 1196

Пример настроек:
![2022-04-30_201525](https://user-images.githubusercontent.com/4610098/166115693-bee6a4d4-f59c-4913-998f-528cc8bfb63c.png)
![2022-04-30_201604](https://user-images.githubusercontent.com/4610098/166115694-8665e158-cac7-4488-a860-5b904bf84844.png)
![2022-04-30_201642](https://user-images.githubusercontent.com/4610098/166115695-8205004f-3b52-47b5-b099-470b44f15d21.png)
![2022-04-30_201654](https://user-images.githubusercontent.com/4610098/166115697-f6223b7d-ceb9-445d-b0dd-eb0379e69b91.png)

**Comment by luxeceiling** [comment]
Спасибо большое! с последними изменениями все заработало

**Comment by luxeceiling** [comment]
С меня Donate
