### ISSUE TITLE
Добавьте, пожалуйста, amlgames.com

### ISSUE THREAD

**Issue by Dramorian** [zhovner/zaborona_help#264]
178.20.40.0/24
178.20.40.0 - 178.20.40.255

**Comment by toxi22** [comment]
> 178.20.40.0/24
> 178.20.40.0 - 178.20.40.255

Добавили. Проверьте, работает ли сайт

**Comment by Dramorian** [comment]
> Добавили. Проверьте, работает ли сайт

Работает. Спасибо.
