### ISSUE TITLE
3dtoday.ru

### ISSUE THREAD

**Issue by Vicsar73** [zhovner/zaborona_help#266]
Доброго времени, добавьте пожалуйста 3dtoday.ru
Спасибо.

**Comment by toxi22** [comment]
> Доброго времени, добавьте пожалуйста 3dtoday.ru
> Спасибо.

Добавили. Переподключитесь и проверьте, пожалуйста, как работает сайт

**Comment by Vicsar73** [comment]
спасибо. заработало.
