### ISSUE TITLE
Еще один заблокированый сайт

### ISSUE THREAD

**Issue by lUjek-Sh** [zhovner/zaborona_help#273]
Некоторые подоменни сайта datalock.ru
К примеру:
http://temp-cdn.datalock.ru
http://data08-cdn.datalock.ru
и т.д.

А вот http://data05-cdn.datalock.ru работает нормально.

**Comment by toxi22** [comment]
> Некоторые подоменни сайта datalock.ru К примеру: http://temp-cdn.datalock.ru http://data08-cdn.datalock.ru и т.д.
> 
> А вот http://data05-cdn.datalock.ru работает нормально.

Добавили. Просьба, проверить, работают ли остальные сайты

**Comment by lUjek-Sh** [comment]
> Добавили. Просьба, проверить, работают ли остальные сайты

Вы добавили только 2 доменна? или все возможные? (*.datalock.ru)

**Comment by toxi22** [comment]
> Вы добавили только 2 доменна? или все возможные? (*.datalock.ru)

Добавили все поддомены, которые нашли:
```
datalock.ru
rec.datalock.ru
data-hd.datalock.ru
data10-cdn.datalock.ru
data01-cdn.datalock.ru
data11-cdn.datalock.ru
data02-cdn.datalock.ru
data12-cdn.datalock.ru
data05-cdn.datalock.ru
data06-cdn.datalock.ru
www.datalock.ru
```

**Comment by lUjek-Sh** [comment]
> 


> Добавили все поддомены, которые нашли:

Вот я нашел такие еще:

data03-cdn.datalock.ru
data04-cdn.datalock.ru
data06-cdn.datalock.ru
data09-cdn.datalock.ru
data12-cdn.datalock.ru
data13-cdn.datalock.ru
ns1.datalock.ru --- это под вопросом нужно ли вообще добавлять или нет.

**Comment by toxi22** [comment]
> data03-cdn.datalock.ru
> data04-cdn.datalock.ru
> data06-cdn.datalock.ru
> data09-cdn.datalock.ru
> data12-cdn.datalock.ru
> data13-cdn.datalock.ru

Эти адреса попадают под тот же диапазон:
```
# *.datalock.ru
push "route 193.33.170.0 255.255.254.0" # AS42775 - 193.33.170.0/23 - ADWORLDS TECHNOLOGIES LP
push "route 62.76.24.0 255.255.252.0" # AS61400 62.76.24.0/22 - Start LLC
push "route 146.255.197.0 255.255.255.0" # AS42632 - 146.255.197.0/24 - MnogoByte colocation and dedicated
```

**Comment by lUjek-Sh** [comment]
> Эти адреса попадают под тот же диапазон

Тогда ок. Я просто проверял через ping. И ответа от сервера не было

**Comment by toxi22** [comment]
> Тогда ок. Я просто проверял через ping. И ответа от сервера не было

Если что, сообщайте :)

**Comment by lUjek-Sh** [comment]
> Если что, сообщайте :)

Хорошо)
