### ISSUE TITLE
Еще один сайт

### ISSUE THREAD

**Issue by lUjek-Sh** [zhovner/zaborona_help#275]
Прошу внести еще один сайт
https://apptractor.ru

**Comment by lUjek-Sh** [comment]
А также vs1.cdnsqu.com возможно есть другие поддомены

**Comment by toxi22** [comment]
> Прошу внести еще один сайт https://apptractor.ru

Добавили. Так же несколько серверов находятся в Украине и Нидерландах (мы их исключили из выдачи маршрутов):
```
# apptractor.ru - AS210079 (hosted-by.ihc.ru); AS50499 (k31.hostenko.com, Canada); AS21100 (ITL LLC, Kharkov, Ukraine)	
push "route 95.183.13.0 255.255.255.0"
#push "route 193.106.248.0 255.255.255.0" # ? Ukraine
#push "route 185.14.28.0 255.255.252.0" # ? Netherlands
```
Если Вам нужны отключенные маршруты, можете самостоятельно добавить в конфиг-файл указанные маршруты и удалить знак "#" (решетка) вначале строки, если Вам они будут необходимы.


> А также vs1.cdnsqu.com возможно есть другие поддомены

Сайт находится на Украинском хостинге и на серверах в Нидерландах и используется для раздачи торрента:
Указанный субдомен vs1.cdnsqu.com - не существует:
`We can't resolve the domain vs1.cdnsqu.com! Please try your query again.`
Мы их не прописывали в разрешенные, так как этот сайт не имеет отношения к заблокированным и не относится к РФ.
