### ISSUE TITLE
Не получаеться настроть ASUSWRT HELP!

### ISSUE THREAD

**Issue by deniben** [zhovner/zaborona_help#282]
![image](https://user-images.githubusercontent.com/19304301/170079139-22ce02c9-c975-4efc-b4ad-ee78fc34f20d.png)
![image](https://user-images.githubusercontent.com/19304301/170079174-aecadc30-d4fe-4134-8213-e600fe7975e1.png)
![image](https://user-images.githubusercontent.com/19304301/170079271-dba14eb3-21a4-489f-a671-8c0bd1392e09.png)
![image](https://user-images.githubusercontent.com/19304301/170079319-a325e800-a486-4abb-ab07-507d73ff43f2.png)
Я даже не знаю что ещё вам показать, все профили вгружал как проверить? Галочки синей нету как у других.
VPN sever and PPTP отключены.
Остальное на скринах видно, буду благодарен

**Comment by toxi22** [comment]
> ![image](https://user-images.githubusercontent.com/19304301/170079174-aecadc30-d4fe-4134-8213-e600fe7975e1.png)

Добрый день.
Попробуйте здесь наоборот, включить IPv6, но не настраивать его. Насколько помню, там есть режим Microsoft Legacy (что-то похожее)

**Comment by deniben** [comment]
Поставил Европ. профиль 
![image](https://user-images.githubusercontent.com/19304301/170085667-cc2a98b9-232a-4d82-8440-c385833462c4.png)
![image](https://user-images.githubusercontent.com/19304301/170085749-d8df10cb-0b35-463a-baa2-a7f539fd2eb7.png)

**Comment by deniben** [comment]
Проблема решена:

Заходте в файл [srv0.zaborona-help_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/srv0.zaborona-help_maxroutes.ovpn) или UDP: [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn)
и вместо ```#max-routes 25000``` делаем ```max-routes 25000```

Туц - https://github.com/zhovner/zaborona_help/wiki/OpenVPN-ROUTE:-cannot-add-more-than-100-routes.-Please-increase-the-max-routes-option-in-the-client-configuration-file
