### ISSUE TITLE
Яндекс Музыка пустые плейлисты с socks.zaboronahelp.pp.ua Socks5 прокси из Украины

### ISSUE THREAD

**Issue by bahusoid** [zhovner/zaborona_help#289]
С socks.zaboronahelp.pp.ua:1488 (Европейский Socks5) Яндекс Музыка частично работает. Работает Моя волна. Но все ежедневные плейлисты (например Плейлист дня) и подборки пустые:

![EmptyPlaylist](https://user-images.githubusercontent.com/22025304/172013731-66f73f06-5f78-45a8-b77b-e926efd48f4c.jpg)

Заметил обращение к следующим серверам:

1) api.music.yandex.net
87.250.250.246 
IP диапазон 87.250.249.192-87.250.251.255

2) strm.yandex.net
87.250.254.45
IP диапазон 87.250.254.0-87.250.255.255

**Comment by toxi22** [comment]
Добрый день.
Добавили маршруты. Проверьте, пожалуйста, есть ли какие-то изменения?

**Comment by bahusoid** [comment]
Плейлист дня - пусто :( Но какие-то плейлисты таки открываются  - плейлисты Премьера и Подкасты нормально открылся.  

Если я запущу какой-нить Европейский VPN  и оставлю socks.zaboronahelp.pp.ua, то плейлисты остаются пустые. Т.е. похоже с этим socks5 прокси плейлисты поломаны не только в Украине.

У меня все ОК напрямую через Европейский VPN (пробовал сервера из Люксембург и Польша) и Европейский VPN + socks.zaborona.help 

Речь об Android приложении.

**Comment by toxi22** [comment]
> Плейлист дня - пусто :( Но какие-то плейлисты таки открываются - плейлисты Премьера и Подкасты нормально открылся.

Спасибо за информацию, будем проверять еще
