### ISSUE TITLE
Добавьте домен spletnik.ru

### ISSUE THREAD

**Issue by Anian-igor** [zhovner/zaborona_help#298]
Добавьте пожалуйста spletnik.ru
89.208.156.205

**Comment by toxi22** [comment]
Добрый день.
Добавим в ближайшем обновлении.
Спасибо за информацию :)

**Comment by toxi22** [comment]
> Добавьте пожалуйста spletnik.ru 89.208.156.205

Добрый день.
Добавили. Проверьте, пожалуйста, работу сайта

**Comment by Anian-igor** [comment]
Работает
