### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by lUjek-Sh** [zhovner/zaborona_help#300]
Trying connect to 88.212.244.156 port 443 failed: Timed out

stat.dl.mail.ru
dl.mail.ru 
static.dl.mail.ru  
stat.dl.mail.ru 

Возможно есть еще под домены.

**Comment by toxi22** [comment]
Добрый день.
Спасибо за информацию. Проверим

**Comment by toxi22** [comment]
Обновили. Они впринципе все относятся к Mail.ru. Проверьте, пожалуйста, работают ли данные сайты после обновления маршрутов

**Comment by lUjek-Sh** [comment]
![image](https://user-images.githubusercontent.com/64215831/179320090-46a81430-d145-4a99-bde2-7add3048babd.png)
Вроде работает
