### ISSUE TITLE
Перестал работать доступ на Keenetic Viva (KN-1910)

### ISSUE THREAD

**Issue by Berzerk3r** [zhovner/zaborona_help#334]
После обновления прошивки не хочет подключаться.
Как я поянл лиз-за обновления клиента OpenVPN в прошивке.
Если тупо в лоб закомментировать строчку `#setenv opt block-outside-dns` в конфиге - коннект проходит, но сайты естественно не грузятся. Кусок лога прилагаю

```
Дек 16 01:51:47
OpenVPN0
Unrecognized option or missing or extra parameter(s) in configuration: (line 16): block-outside-dns (2.6_git)
Дек 16 01:51:47
OpenVPN0
Exiting due to fatal error
Дек 16 01:51:47
ndm
Service: "OpenVPN0": unexpectedly stopped.
Дек 16 01:51:47
ndm
Network::Interface::OpenVpn: "OpenVPN0": configuration is invalid. 
```

**Comment by toxi22** [comment]
Добрый день.
Верно, строку `#setenv opt block-outside-dns` нужно закомментировать либо удалить.

По поводу неработающих сайтов - в новой версии Keenetik OS обновили openvpn клиент до версии 2,6, из-за этого, некоторые параметры и алгоритмы шифрования изменились. На днях запустим дополнительный сервер с сервером openvpn 2.6, который сможет решить проблему с сайтами. Пока только ждать.

**Comment by Berzerk3r** [comment]
Спасибо за быструю реакцию! Закрываю.
