### ISSUE TITLE
Настройка openvpn client на шлюзе centos/clearos

### ISSUE THREAD

**Issue by YADeM** [zhovner/zaborona_help#37]
Всем добрый день!
Подскажите не могу никак понять почему не ходят пакеты из сети в туннель
Есть шлюз на clearos, настроено, работает.
Openvpn с настройками на заборону - работает, но только с сервера, из сети, если даже и работали какие-то домены - то перестают.

> iptables -t nat -A POSTROUTING -o tun2 -j MASQUERADE

не помогло
Кто-то может подсказать почему? Т.к. хочу понять свой сервер для офиса, но перед этим, хочу потренироваться.

**Comment by qwertyhansindar** [comment]
ну чтоб понять нужны данные.
ip a

конфиг openvpn
и iptables в студию
посмотрим подумаем

я поднял по аналогии, но чисто для себя - всё работает отлично

**Comment by YADeM** [comment]
@qwertyhansindar Грешу на то, что это же не centos чистый, а clearos https://en.wikipedia.org/wiki/ClearOS
может у него свои тараканы есть (((

**Comment by qwertyhansindar** [comment]
а кто роуты на tun2 прописывал?

**Comment by YADeM** [comment]
подтягивались из конфига openvpn,  этого https://raw.githubusercontent.com/zhovner/zaborona_help/master/zaborona-help.ovpn

**Comment by YADeM** [comment]
я вот думаю, может стоит прописать NAT PREROUTIG с -d сетями и пихать все это в tun2?

**Comment by qwertyhansindar** [comment]
я не вижу в FORWARD tun2

**Comment by YADeM** [comment]
iptables -A FORWARD -o tun2 -j ACCEPT
iptables -A FORWARD -i tun2 -j ACCEPT
?

**Comment by YADeM** [comment]
> 
> Chain FORWARD (policy DROP 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.117        tcp dpt:9000
>    57  4028 ACCEPT     udp  --  *      enp1s0  0.0.0.0/0            192.168.0.35         udp dpts:10000:20000
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.10         tcp dpt:443
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.11         tcp dpt:3142
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.11         tcp dpt:8888
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.11         tcp dpt:21
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.11         tcp dpt:22
>    48 19702 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.35         tcp dpt:5061
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.35         tcp dpt:80
>    58 18025 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.65         tcp dpt:8080
>     4   215 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.13         tcp dpt:3389
>   150 44374 ACCEPT     udp  --  *      enp1s0  0.0.0.0/0            192.168.0.12         udp dpt:1194
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.12         tcp dpt:1194
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.12         tcp dpt:22
>     0     0 ACCEPT     tcp  --  *      enp1s0  0.0.0.0/0            192.168.0.203        tcp dpt:7575
>     0     0 DROP       tcp  --  *      *       192.168.0.0/24       0.0.0.0/0            tcp dpt:139
>     0     0 DROP       tcp  --  *      *       192.168.0.0/24       0.0.0.0/0            tcp dpt:445
> 41428   14M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
>     0     0 ACCEPT     all  --  pptp+  *       0.0.0.0/0            0.0.0.0/0
>    25  1679 ACCEPT     all  --  tun+   *       0.0.0.0/0            0.0.0.0/0
>  1856  531K ACCEPT     all  --  enp1s0 *       0.0.0.0/0            0.0.0.0/0
>     0     0 ACCEPT     all  --  tun2   *       0.0.0.0/0            0.0.0.0/0
>     0     0 ACCEPT     all  --  *      tun2    0.0.0.0/0            0.0.0.0/0
>

**Comment by YADeM** [comment]
я блин альтернативно одаренный (((
разобрался, поднял FORWARD вверх и все зашевелилось
Теперь начинаем мучения со своим vpn сервером
@qwertyhansindar спасибо за помощь!
