### ISSUE TITLE
Rezka.Ag

### ISSUE THREAD

**Issue by lUjek-Sh** [zhovner/zaborona_help#389]
rezka.ag под vpn выводит сообщения "К сожалению, это видео не доступно в вашем регионе"
Если впн выключить то все работает. Поиск по репозиторию привел меня к сообщению https://github.com/zhovner/zaborona_help/issues/208#issuecomment-1097427371

Так же методом тыка нашел что через впн идет только этот ip адрес 176.58.50.0

Прошу убрать или на оборот добавить остальные ip в конфиг

**Comment by toxi22** [comment]
Добрый десь.
Спасибо за инфорамцию, уберу в ближайшее время

**Comment by lUjek-Sh** [comment]
> Добрый день. Спасибо за инфорамцию, уберу в ближайшее время

Возможно нужно добавить остальные ip. В данном вопросе я не разбираюсь так что решение за вами нужно удалить или добавить

**Comment by toxi22** [comment]
> > Добрый день. Спасибо за инфорамцию, уберу в ближайшее время
> 
> Возможно нужно добавить остальные ip. В данном вопросе я не разбираюсь так что решение за вами нужно удалить или добавить

Окей. Для начала уберу, понаблюдаем

**Comment by lUjek-Sh** [comment]
> > > Добрый день. Спасибо за инфорамцию, уберу в ближайшее время
> > 
> > 
> > Возможно нужно добавить остальные ip. В данном вопросе я не разбираюсь так что решение за вами нужно удалить или добавить
> 
> Окей. Для начала уберу, понаблюдаем

Вот еще что: Через хром нетворк увидел что видео идет от сюда
https://acheron.stream.voidboost.cc

**Comment by toxi22** [comment]
Убрал адрес `176.58.50.0` и домен `*.voidboost.cc`
