### ISSUE TITLE
Добавить заблокированный ресурс

### ISSUE THREAD

**Issue by Traine9** [zhovner/zaborona_help#399]
https://pikabu.ru
91.215.42.110
раньше работал теперь перестал видимо сменился ip

**Comment by toxi22** [comment]
Спасибо за информацию. Проверю

**Comment by toxi22** [comment]
> https://pikabu.ru 91.215.42.110 раньше работал теперь перестал видимо сменился ip

Проверьте, заработал ли сайт

**Comment by Traine9** [comment]
заработал, спасибо
