### ISSUE TITLE
Сижу через openvpn, постоянно кидает на моб. версии сайтов.

### ISSUE THREAD

**Issue by journeym** [zhovner/zaborona_help#402]
Например вк:
![image](https://user-images.githubusercontent.com/7759734/230716964-b379b63d-aec7-46d7-b021-57ac6971ca1a.png)
Как это обойти?

**Comment by toxi22** [comment]
А расширение для ВК никакие не установлены?
Проверил через Хром - проблемы нет с переадресацией на мобильную версию. Еще может быть, что Вы раньше заходили на мобильную версию и ВК запомнил этот выбор и постоянно перевидывает Вас на мобильныую версию.
![2023-04-10_195427](https://user-images.githubusercontent.com/4610098/230950918-489921e4-10b8-4545-bc3c-fe3e83b0ca5e.png)
