### ISSUE TITLE
микротик rutube

### ISSUE THREAD

**Issue by journeym** [zhovner/zaborona_help#406]
По гайду микротика все пашет, но рутуб не прогружается до конца, при этом через openvpn c того же компа все ок.
https://github.com/zhovner/zaborona_help/wiki/Mikrotik
Что это может быть?
![image](https://user-images.githubusercontent.com/7759734/233198664-44da424e-e768-4897-8e10-ea46ba0c4d3f.png)

**Comment by journeym** [comment]
По ходу микротик гайд не рабочий, подмены ip в выдаче dns не происходит, если настроить по инструкции.

**Comment by journeym** [comment]
Короче непонятно, vk пашет rutube нет через mikrotik по гайду, пробовал преподклбючать vpn на рутере и т.д., не помогает. В браузер консоли таймауты на **static.rutube.ru**, **pic.rutubelist.ru** При этом через openvpn-client пашет все.

**Comment by toxi22** [comment]
Добрій день.
Проблема может быть связана с тем, что Микротик использует ДНС сервера в режиме roundrobin.
У меня такая же проблема на Микротике. Решил пока проблему тем, что в настройках DHCP-сервера прописал ДНС сервера забороны, чтобы они выдавались клиентам и проблема с работой заблокированных сайтов проявляется редко.

**Comment by journeym** [comment]
Да, помогло, спасибо.
Может добавить в вики по микротику?
