### ISSUE TITLE
насчет андроид 4.4

### ISSUE THREAD

**Issue by chipitsine** [zhovner/zaborona_help#41]
у меня нет под руками именно 4.4 (чтобы проверить https://github.com/zhovner/zaborona_help/wiki/Android-4.4 )

пробовали такую настройку ?

route-metric 100

или вот этого клиента ?

https://play.google.com/store/apps/details?id=de.blinkt.openvpn&hl=ru

(в нашем случае оказалось, что в отличие от openvpn connect, он сохраняет пароли)

**Comment by zhovner** [comment]
У меня тоже нет, нужно позвать тех у кого есть.
