### ISSUE TITLE
Оптимизация маршрутов

### ISSUE THREAD

**Issue by kilroy98** [zhovner/zaborona_help#434]
Не знаю конечно оптимально это или нет, но для начала решил парочку подсетей сделать:

`CIDR Range - 5.45.192.0/18 / Netmask - 255.255.192.0`
`CIDR Range - 178.154.128.0/17 / Netmask - 255.255.128.0`
`CIDR Range - 185.32.184.0/22 / Netmask - 255.255.252.0`
`CIDR Range - 193.32.216.0/22 / Netmask - 255.255.252.0`
`CIDR Range - 130.193.32.0/19 / Netmask - 255.255.224.0`

Информацию по IP-адресам брал на bgp.he.net (не знаю, можно ли считать информацию с него достоверной).

И чисто как предложение, думаю стоит немного подчистить файл https://github.com/zhovner/zaborona_help/blob/1c8f5af6b165ea0575ecb8e179d0231567ed5bf3/config/openvpn/ccd3-4_max_routes/DEFAULT
Всё же слишком много мусора там уже, в начале файла маршруты могут быть закомментированы, но дальше в файле опять же они есть и уже не закомментированы. Понимаю, что на работу они никак не влияют, но думаю вам и самому будет куда приятнее работать с этим файлом, да и пользователям, которые захотят помочь с оптимизацией маршрутов, будет легче.

**Comment by raddyst** [comment]
> И чисто как предложение, думаю стоит немного подчистить файл [ccd3-4_max_routes/DEFAULT](https://github.com/zhovner/zaborona_help/blob/1c8f5af6b165ea0575ecb8e179d0231567ed5bf3/config/openvpn/ccd3-4_max_routes/DEFAULT)

Удачи ) Может хоть тут получится оперативнее.

**Comment by toxi22** [comment]
> И чисто как предложение, думаю стоит немного подчистить файл https://github.com/zhovner/zaborona_help/blob/1c8f5af6b165ea0575ecb8e179d0231567ed5bf3/config/openvpn/ccd3-4_max_routes/DEFAULT Всё же слишком много мусора там уже, в начале файла маршруты могут быть закомментированы, но дальше в файле опять же они есть и уже не закомментированы. Понимаю, что на работу они никак не влияют, но думаю вам и самому будет куда приятнее работать с этим файлом, да и пользователям, которые захотят помочь с оптимизацией маршрутов, будет легче.

Спасибо за информацию)



> Удачи ) Может хоть тут получится оперативнее.

За ваше сообщение я тоже помню, но пока чистка занятулась по времени)
