### ISSUE TITLE
конфиг для Tunnelblick

### ISSUE THREAD

**Issue by chipitsine** [zhovner/zaborona_help#45]
привет!

предлагаю вместо *.ovpn давать ссылку на *.tblk.zip

https://github.com/Tunnelblick/Tunnelblick/issues/382

в tblk можно протащить настройку, отключающую проверку на то, поменялся ли внешний адрес (и, при желании любые настройки)

**Comment by zhovner** [comment]
Хорошая идея. Сделайте конфиг и мы его опубликуем.

**Comment by chipitsine** [comment]
Почему сами конфиг не сделаете?

**Comment by zhovner** [comment]
Готово https://zaborona.help/macos.html
