### ISSUE TITLE
Добавьте пожалуйста сайты по Left 4 Dead и Old-Games

### ISSUE THREAD

**Issue by kworkerz** [zhovner/zaborona_help#455]
Если будет возможность, добавьте пожалуйста сайты игровой тематики. Спасибо!
zozo.gg
forum.zozo.gg
wargm.ru

**Comment by kworkerz** [comment]
Эх, жаль, никакого ответа.
Если что, это не казино и не азартные игры.
Это сайты по игре в старый зомби-шутер Left 4 Dead.
Хотелось бы к серверам zozo подключаеться, во время игры трафик мизерный.

Также не открывается сайт и форум по ретро-играм:
https://www.old-games.ru
https://www.old-games.ru/forum

Если будет возможность их включить в конфиг, было бы круто!
Спасибо!

**Comment by raddyst** [comment]
> Это сайты по игре в старый зомби-шутер Left 4 Dead.
> Хотелось бы к серверам zozo подключаеться, во время игры трафик мизерный.

Сомневаюсь, что пинг устроит... 

> Также не открывается сайт и форум по ретро-играм: https://www.old-games.ru https://www.old-games.ru/forum
> 
> Если будет возможность их включить в конфиг, было бы круто!

Эти как раз добавлены и работают.
