### ISSUE TITLE
Заблокированный ресурс

### ISSUE THREAD

**Issue by Dramorian** [zhovner/zaborona_help#467]
Не работает домен закачки файлов на rsload.net.

https://f1.1rsload.ru/
5.189.239.173

**Comment by Dramorian** [comment]
А не, работает на [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn) конфиге.

**Comment by raddyst** [comment]
> А не, работает на [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn) конфиге.

Работает и на стандартном srv0.zaborona-help_maxroutes.ovpn - только через него регулярно удаётся попасть на неработающие сервера.

**Comment by toxi22** [comment]
> > А не, работает на [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn](https://zaborona.help/openvpn-client-config/srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn) конфиге.
> 
> Работает и на стандартном srv0.zaborona-help_maxroutes.ovpn - только через него регулярно удаётся попасть на неработающие сервера.

Если проблема повторится с неработающими серверами, сообщите, пожалуйста.
Убрал неработающие сервера из списка
