### ISSUE TITLE
Актуальные адреса роутинга

### ISSUE THREAD

**Issue by Aligatro** [zhovner/zaborona_help#47]
Добрый вечер, могли бы вы пожалуйста обновить config с маршрутами для openvpn, так как в текущей версии практически все сервисы mail.ru не резолвятся. 

Спасибо.

**Comment by zhovner** [comment]
Что вы имеете в виду? Резолвятся домены через DNS серверы. 
Как воспроизвести проблему о которой вы говорите?

**Comment by Aligatro** [comment]
Всмысле с настройками роутинга из [текущего конфига](https://github.com/zhovner/zaborona_help/blob/master/config/openvpn/ccd/DEFAULT), сервисы mail'a не доступны. При этом если подключится к вашему серверу. все работает нормально.

**Comment by zhovner** [comment]
Актуальный список здесь https://zaborona.help/ips.txt
Конфиг обновлю позже.

**Comment by Aligatro** [comment]
Понял, благодарю за помощь.

**Comment by ImCatzilla** [comment]
А у меня и с текущим конфигом все сервисы mail'а прекрасно работают.

Однако, обнаружил следующие диапазоны, принадлежащие mail.ru, и отсутствующие в конфиге:
```
185.6.244.0/22
185.30.176.0/22
195.218.190.0/23
2a04:4b40::/29
```
Не знаю, используются ли они какими-то публичными сервисами, однако whois мэйловский.

**Comment by Aligatro** [comment]
В целом проблему решил. Не знаю по какой причине но до добавления HE.net dns серверов в конфиг сервера, для mail.ru у меня резовлился такой ip - 52.28.84.198. Добавил вторые dns и всё заработало. 
Еще раз спасибо за помощь и за инициативу в целом, ваш проект и труд достоин уважения. 
Желаю удачи.

**Comment by zhovner** [comment]
IP адрес 52.28.84.198 принадлежит Amazon. Видимо Mail.ru пытается самостоятельно обойти блокировки в Украине как это делал яндекс.
Здесь видно, что этот IP адрес возвращается только при запросе из Украины https://www.host-tracker.com/InstantCheck/ResultComplete/d475e10c-5b56-e711-b124-0003ff7328cc 

Рекомендую вам очистить DNS кеш.

**Comment by zhovner** [comment]
@ImCatzilla Добавил эти сети.
