### ISSUE TITLE
Прошу добавить еще одну подсеть

### ISSUE THREAD

**Issue by iatalmid** [zhovner/zaborona_help#48]
193.0.170.0/23

**Comment by zhovner** [comment]
Эта сеть принадлежит Mamba.ru. 
На сколько мне известно, этот сайт не должен быть забанен. Какой у вас провайдер?

**Comment by iatalmid** [comment]
http://datanet.kiev.ua/

-- 


Best regards, Igor Alyushev

http://kemokiev.org

ICQ: 			312852229
skype: 			iatalmid
sipnet: 			2162395 ext. 2014
Home phone: 		+380(4572)7-57-19
USA phone:		+1(323)825-95-03
Cell: 			+380(63)578-31-76
Ukraine phone: 	+380(44)374-02-43 ext. 2014
Ukraine mobile: 	+380(93)177-0-257 ext. 2014
Italy phone: 		+39(020)061-37-08 ext. 2014
Poland phone: 	+48(22)382-59-09 ext. 2014
Germany phone: 	+498972101074099 ext. 2014
Russian phone: 	+7(812)458-43-06 ext. 2014
France: 			+33(98)030-05-03
Israel: 			+972(79)574-2135

**Comment by qwertyhansindar** [comment]
Провайдер Воля, Харьков - всё работает.
Советую вам сделать как сделал я в своё время - когда воля заблокировала всю подсеть вместе с кучей сайтов.

Пишите заявление от своего имени в свободном формате
Заявление на имя.....
Я такой то такой то, проживаю там то и являюсь клиентом вашей организаци... логин такой то(зависит от того как вас там идентифицируют как клиента)
С такого то числа не получаю доступ к ресурсу такому то. Согласно УКАЗ ПРЕЗИДЕНТА УКРАЇНИ №133/2017 данный ресурс не находится в списках блокировки, а потому его блокировение НЕ законно и нарушает мои конституционные права о свободе сбора и распространения информации, так же вы предоставляете НЕ полную/Не качественную услугу, а значит взымать оплату в полном объеме не можете ну и дальше требование аргументировать блокирование ресурса и компенсировать причиненные неудобства. далее ОБЯЗАТЕЛЬНО пишите
что согласно закону Украины про обращение граждан статьи 18 вы требуете удовлетворить ваше право на получение письменного ответа не позднее чем установленные законом сроки (статья 20 закона Об обращении граждан) , и что Статья 19 прямо ОБЯЗУЕТ дать вам письменный ответ.

Указываете полный адрес город улица индекс, чтоб могли отправить вам письмо. Это переведёт разговор из ну вы идите мы всё решим в юридическое русло. читайте 5 статью - что должно быть указано в обращении чтоб вашим заявлением не подтёрлись.

Мне хватило устно по телефону надиктовать, чтоб через 2 или 3 часа всё починили и еще компенсировали 3 дня пользования.

**Comment by zhovner** [comment]
Они ответили, что Mamba.ru не блокируется.

![](https://monosnap.com/file/9TejgUYNk2ivNwSCHzgcfHAvGFLHLf.png)

**Comment by qwertyhansindar** [comment]
Нужно от хоста у которого проблемы проверять traceroute
именно так я выяснил что проблема в volya была, до киева уходил запрос, а дальше дох на их сервере

**Comment by iatalmid** [comment]
Не все так просто. 
Вся подсеть действительно принадлежит mamba
Однако часть адресов используются для love.mail.ru <http://love.mail.ru/>

host mamba.ru
mamba.ru has address 193.0.170.24
mamba.ru has address 193.0.170.23

host love.mail.ru
love.mail.ru has address 193.0.170.27
love.mail.ru has address 193.0.170.28


Mamba действительно работает. А вот love.mail.ru <http://love.mail.ru/> - нет. Причем дело не в DNS

traceroute love.mail.ru
traceroute: Warning: love.mail.ru has multiple addresses; using 193.0.170.27
traceroute to love.mail.ru (193.0.170.27), 64 hops max, 52 byte packets
 1  h (192.168.118.254)  2.028 ms  0.736 ms  0.673 ms
 2  cirin-24-1.cosmonova.net.ua (95.67.24.1)  1.063 ms  2.299 ms  1.171 ms
 3  192.168.44.1 (192.168.44.1)  0.883 ms  3.433 ms  1.787 ms
 4  gw-cirin.cosmonova.net.ua (95.67.4.165)  1.365 ms  1.546 ms  1.341 ms
 5  blocked.cosmonova.net.ua (95.67.2.86)  1.541 ms  1.429 ms  1.201 ms
 6  blocked.cosmonova.net.ua (95.67.2.86)  1.217 ms  1.142 ms  1.839 ms



Разумеется на мой запрос провайдер ответит: mamba не блокируется, все хорошо.
А вот хосты mail.ru <http://mail.ru/> - таки да
-- 


Best regards, Igor Alyushev

http://kemokiev.org

ICQ: 			312852229
skype: 			iatalmid
sipnet: 			2162395 ext. 2014
Home phone: 		+380(4572)7-57-19
USA phone:		+1(323)825-95-03
Cell: 			+380(63)578-31-76
Ukraine phone: 	+380(44)374-02-43 ext. 2014
Ukraine mobile: 	+380(93)177-0-257 ext. 2014
Italy phone: 		+39(020)061-37-08 ext. 2014
Poland phone: 	+48(22)382-59-09 ext. 2014
Germany phone: 	+498972101074099 ext. 2014
Russian phone: 	+7(812)458-43-06  ext. 2014
France: 			+33(98)030-05-03
Israel: 			+972(79)574-2135

**Comment by zhovner** [comment]
Добавлены адреса love.mail.ru. Для применения изменений переподключитесь к VPN.

**Comment by zhovner** [comment]
Сети mamba.ru удалены из-за проблем https://github.com/zhovner/zaborona_help/issues/59
