### ISSUE TITLE
Добавить поддержку Anixart в [zm_ua.ovpn]

### ISSUE THREAD

**Issue by mak7im01** [zhovner/zaborona_help#481]
Здравствуйте. При включенной конфигурации [zm_ua.ovpn] свободно заходил в программу Anixart, теперь же не подключается. Проблема началась три дня назад. На конфигурации [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn] заходит без проблем и работает но через данную конфигурацию не работает 4PDA. Очень прошу поправить [zm_ua.ovpn]

**Comment by raddyst** [comment]
> но через данную конфигурацию не работает 4PDA.

4pda.to должен работать без впн и профили забороны на доступ к ресурсу не влияют.

**Comment by mak7im01** [comment]
4pda.to через [zm_ua.ovpn] моментально открывается, а через [srv0.zaborona-help-UDP-no-encryption_maxroutes.ovpn] очень долго открывается (как и без него). Именно за приложение говорю.
