### ISSUE TITLE
xUbuntu 16.04.2 через время перестаёт работать

### ISSUE THREAD

**Issue by GoodGuyNick** [zhovner/zaborona_help#49]
Xubuntu 16.04.2. Всё установлено в соответствии с инструкцией. Через определённое время VPN перестаёт обходить блокировку. VPN включен, на обычные сайты заходит нормально, на заблокированные перестаёт заходить.

**Comment by zhovner** [comment]
Вам придется самому установить причину почему обход блокировки перестает работать.
Проверьте таблицу маршрутов `route print`, на какие адреса резолвятся запрещенные домены а также работает ли VPN тоннель. Для проверки можете попинговать адрес сервера через tun интерфейс.

**Comment by zhovner** [comment]
Выясните как именно ваш провайдер блокирует сайты. Если DNS запросы перехватываются, убедитесь, что DNS запрос идут именно через тоннель. Полагаю что с определенным интервалом (Lease timeoute DHCP?) у вас происходит какое-то событие, в результате чего переназначаются маршруты или DNS сервер, может и то и другое.

**Comment by GoodGuyNick** [comment]
Проблема явно в моей убунте, так как в виртуалке всё норм.
