### ISSUE TITLE
С включённым VPN очень сильно тормозит закачка видео используя youtube-dl

### ISSUE THREAD

**Issue by GoodGuyNick** [zhovner/zaborona_help#50]
Проверил на других конфигах от других серваков, проблема наблюдается только с вашим конфигом. Тестил на разных видео.
Включён VPN. Пытаюсь скачать видео с ютуба используя youtube-dl. 
```
user@user:~$ youtube-dl -f bestvideo+bestaudio/best https://www.youtube.com/watch?v=nhy4Z_32kQo
[youtube] nhy4Z_32kQo: Downloading webpage
[youtube] nhy4Z_32kQo: Downloading video info webpage
[youtube] nhy4Z_32kQo: Extracting video information
[youtube] nhy4Z_32kQo: Downloading MPD manifest
```
Вот это всё происходит на протяжении нескольких минут и только через примерно десяток минут, если не больше, начинается загрузка видео.

**Comment by zhovner** [comment]
Вам нужно самому разобраться в причинах такого поведение вашей программы. Включите отладку и выясните чего ждет программа. Проблема явно на вашей стороне и я не могу угадать в чем она заключается.

**Comment by GoodGuyNick** [comment]
Спасибо, разобрался. Проблема оказалась в том, что youtube-dl закачивая видео из ютуба, использовал ipv6 . С использованием ipv4 скорость соединения почти идентична скорости без использования вашего конфига. Я конечно в теме сетей почти не разбираюсь, но я полагаю ваш конфиг являлся причиной проблемы?

**Comment by zhovner** [comment]
Мы анонсируем маршруты только к определенным IPv6 сетям перечисленным здесь http://zaborona.help/ips.txt
Так что через нас нельзя подключится к Youtube используя ipv4 или ipv6.  Если других ipv6 маршрутов у вас не установлено, программа должна была получить ошибку `no route to host` при попытке подключения по ipv6.  

Если она все-таки успешно подключается, значит у вас стоит что-то типа (Miredo)[https://en.wikipedia.org/wiki/Miredo] через адреса которого вы и подключились. Эта программа создает тоннель для поддержки ipv6 в системе и связь через него действительно очень медленная. Наш VPN устанавливает IPv6 DNS резолверы, поэтому некоторые программы могут пробовать подключаться к ipv6 адресам, однако это не должно влиять на работу если  Miredo не используется.

Покажите вывод команды `ip address` в консоле в момент подключенного VPN.

**Comment by GoodGuyNick** [comment]
Miredo не установлен.
```
user@user:~$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 8c:dc:d4:72:0c:b5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.49/24 brd 192.168.1.255 scope global dynamic eno1
       valid_lft 80031sec preferred_lft 80031sec
    inet6 fe80::986e:c3d1:7aa2:523d/64 scope link 
       valid_lft forever preferred_lft forever
3: wlo1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b0:10:41:2e:91:85 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.1/24 brd 10.42.0.255 scope global wlo1
       valid_lft forever preferred_lft forever
    inet6 fe80::b210:41ff:fe2e:9185/64 scope link 
       valid_lft forever preferred_lft forever
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 52:54:00:a1:c3:8d brd ff:ff:ff:ff:ff:ff
8: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 192.168.225.228/22 brd 192.168.227.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 2a00:1838:30:7200::11e2 peer 2a00:1838:30:7200::1/112 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::e31e:213a:d965:829c/64 scope link flags 800 
       valid_lft forever preferred_lft forever
```

**Comment by ValdikSS** [comment]
`ip -6 r` покажите.

**Comment by GoodGuyNick** [comment]
```
user@user:~$ ip -6 r
2001:678:384::/48 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2001:4860:4860::/64 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2620:10f:d000::/44 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a00:1148::/32 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a00:1838:30:7200::1 dev tun0  proto kernel  metric 256  pref medium
2a00:1838:30:7200::/112 dev tun0  proto kernel  metric 256  pref medium
2a00:a300::/32 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a00:b4c0::/32 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a02:6b8::/32 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a02:5180::/32 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a03:2480::/33 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
2a04:4b40::/29 via 2a00:1838:30:7200::1 dev tun0  proto static  metric 50  pref medium
fe80::/64 dev wlo1  proto kernel  metric 256  pref medium
fe80::/64 dev eno1  proto kernel  metric 256  pref medium
fe80::/64 dev tun0  proto kernel  metric 256  pref medium
default dev tun0  proto static  metric 50  pref medium
```

**Comment by ValdikSS** [comment]
У вас маршрут по умолчанию настроен через VPN. Такого быть не должно. Разибрайтесь, почему так.

**Comment by GoodGuyNick** [comment]
Вы имеете ввиду, что весь трафик идёт через VPN? Если да, то через VPN идут только заблокированные сайты, остальные идут без. Если я пускаю весь трафик через VPN, то открываются только заблокированные ресурсы, остальные не грузит. Я попробовал вручную создать OpenVPN подключение, результат тот же.

**Comment by ValdikSS** [comment]
У вас весь IPv6-трафик идет через VPN. Адресам IPv6 отдается предпочтение выше, чем IPv4. В браузерах реализован механизм happy eyeballs, который пытается открыть сайт одновременно через IPv6 и IPv4, и выбирает тот, который быстрее. Другие системные программы (кроме curl, наверное) такого не делают, и используют IPv6, если возможно, и только потом, при проблемах с ним, переключаются на IPv4.

**Comment by GoodGuyNick** [comment]
Разобрался. Надо обновить мануал для Ubuntu. В "Параметры IPv6" надо сделать то же самое, как в "Параметры IPv4", поставить галку "Use this connection only for resources on its network".

**Comment by zhovner** [comment]
> Надо обновить мануал для Ubuntu. 
Вы можете это сделать самостоятельно. Добавьте только скриншоты.

**Comment by GoodGuyNick** [comment]
обновил наконец-то вики
