### ISSUE TITLE
Wiki настройка Ubuntu Linux 16.04 LTS

### ISSUE THREAD

**Issue by 1Joy1** [zhovner/zaborona_help#52]
В wiki, для установки соеденения клиентом, рекомендуют использовать GUI интерфейс network-manager-openvpn-gnome, но с ним существует проблема, при его использовании клиент не получает все маршруты прописанные в server.conf (push "rout ........")
Если же использовать установку соединения через консоль 
openvpn --config /etc/openvpn/zaborona-help.ovpn то данная проблема отсутствует
На данный момент решение для GUI я не нашел, так что если кому-то есть что посоветовать, с удовольствием выслушаю мнение, ну а если решения нет, то наверное стоит сделать пометку об этом в wiki

**Comment by zhovner** [comment]
Но ведь при подключении через `openvpn --config /etc/openvpn/zaborona-help.ovpn` не устанавливаются DNS резолверы. Для провайдеров, которые перехватывают DNS запросы это не поможет обойти блокировки.

**Comment by Pleskan** [comment]
@1Joy1 
А Вы в свойствах VPN-подключения ставили флажок _"Маршруты" —> "Использовать это соединения только для ресурсов  в этой сети"_ ?

**Comment by 1Joy1** [comment]
**zhovner**
Возможно, не думал об этом. Я сейчас играюсь с вашим и с своим VPN сервисом, у себя в конфиге сервера прописал DNS гугла... на винде вроде работало, а как в ubuntu увидеть какой днс используется незнаю....  cat /etc/resolv.conf выдал мне вообще 127.0.1.1 что с поднятым впн, что без.

**Pleskan**
Да, конечно... Я внимательно читаю мануалы :)
Дело в том, что несколько маршрутов приходит, но далеко не все (с моего впн-а только один, с забороны 5-7) в сети присотствует информация о данной проблеме, но решения нет. Есть только одна рекомендация - использовать консоль.

**Comment by Pleskan** [comment]
> использовать консоль
С учётом использования systemd во всех современных дистрибутивах Linux это вредный совет.
У меня Debian 9, все работает "из коробки". Ради интереса, какой у Вас провайдер?

**Comment by zhovner** [comment]
> cat /etc/resolv.conf выдал мне вообще 127.0.1.1 что с поднятым впн, что без.

У вас наверное стоит dnsmasq через который проксируются запросы. Почитайте справку к пакету `resolvconf` (без точки) и к пакету `dnsmasq`.
Вы можете увидеть какой процесс слушает `127.0.0.1:53` выполнив команду `netstat -ntlup` либо `ss -ntlup` от root-а.

**Comment by 1Joy1** [comment]
@Pleskan 

> Ради интереса, какой у Вас провайдер?
ICN Одесса

@zhovner 

> У вас наверное стоит dnsmasq через который проксируются запросы.
Да, так оно и есть. Почитал маны на скорую руку, понял, что курить нужно тщательней :) в общих чертах осознал что dnsmasq самостоятельно выбирает искать ip-шник у себя в кеше или выбрать один из известных ему днс серверов полученных им разными методами (забитыми в конфигах, полученных по dhcp, etc). Другими словами сам является dns\dhcp сервером.

Таки правильней наверное соединятся через менеджер сетей, осталось теерь только заставить его работать.  Кстати, нашел в своем конфиге на серваке ошибку в маске одного диапазона - исправил... теперь с моего vpn вообще не одного маршрута не получаю. :(

**Comment by 1Joy1** [comment]
От описанной проблемы избавился простой перезагрузкой системы (видимо, как описанно в wiki перелогиниться в системе было недостаточно).
Чтобы не быть голословным проблема известна сообществу. 
https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/1603600

Теперь осталось решить ещё один трабл....
Дело в том, что в конфиге на своем VPN я говорю чтоб маршруты  на smtp сервера яндекса и мейла шли не через vpn а через провайдера. 
`push "route 77.88.21.38 255.255.255.255 net_gateway"     #smtp.yandex.ru
push "route 87.250.250.38 255.255.255.255 net_gateway"   #smtp.yandex.ru
push "route 93.158.134.38 255.255.255.255 net_gateway"   #smtp.yandex.ru
push "route 213.180.193.38 255.255.255.255 net_gateway"  #smtp.yandex.ru
push "route 213.180.204.38 255.255.255.255 net_gateway"  #smtp.yandex.ru
push "route 94.100.180.160 255.255.255.255 net_gateway"  #smtp.mail.ru
push "route 217.69.139.160 255.255.255.255 net_gateway"  #smtp.mail.ru`
Причиной тому то, что во первых мой сервак видимо в бан-спам-блок листе у выше описанных сервисов, а во вторых smtp сервера не заблокированны провайдером, а значит могут не использовать vpn.
В общем network-manager не добавляет эти адреса, отписывая в журнале
`Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9540] platform-linux: do-add-ip4-route[17: 77.88.21.38/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9542] platform-linux: do-add-ip4-route[17: 93.158.134.38/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9545] platform-linux: do-add-ip4-route[17: 213.180.193.38/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9547] platform-linux: do-add-ip4-route[17: 213.180.204.38/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9549] platform-linux: do-add-ip4-route[17: 87.250.250.38/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9551] platform-linux: do-add-ip4-route[17: 217.69.139.160/32 50]: failure 101 (Сеть недоступна)
Июн 26 13:28:23 nout-ubuntu NetworkManager[805]: <error> [1498472903.9553] platform-linux: do-add-ip4-route[17: 94.100.180.160/32 50]: failure 101 (Сеть недоступна)
`
При том пробывал в конфиге писать и так
`push "route 77.88.21.38 255.255.255.255 192.168.1.1" `
результата так же нет. А вот используя openvpn - клиент в консоли, все пушится нормально.
Как то не допиленный этот нетворк менеджер :)

**Comment by 1Joy1** [comment]
Наверное заколлебал уже своими постами :) ну такой уж я дотошный... :) А вдруг комуто пригодится.
На данный момент, как я понял ситуация с network-manager решения не имеет, добавить свои маршруты на локальный интерфейс он не дает. Это подтверждают bug reports:
https://bugzilla.gnome.org/show_bug.cgi?id=758702
https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/1603600
https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1608646
https://bugzilla.redhat.com/show_bug.cgi?id=1417169
Единственный варьянт это реализовать, который я вижу - это добавлять эти маршруты в ручную от рута:
```
route add 77.88.21.38/32 gw 192.168.1.1 dev enp2s0
route add 87.250.250.38/32 gw 192.168.1.1 dev enp2s0
route add 93.158.134.38/32 gw 192.168.1.1 dev enp2s0
route add 213.180.193.38/32 gw 192.168.1.1 dev enp2s0
route add 213.180.204.38/32 gw 192.168.1.1 dev enp2s0
route add 94.100.180.160/32 gw 192.168.1.1 dev enp2s0
route add 217.69.139.160/32 gw 192.168.1.1 dev enp2s0
```
Ну или же использовать openVPN клиент через консоль, а чтобы заработали ДНС резолвs нужно убедится в наличии файла /etc/openvpn/update-resolv-conf и в client.ovpn  раскоментить строки
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

**Comment by msergein** [comment]
Еще вариант отключить dnsmasq:
https://unix.stackexchange.com/a/335613

> Open /etc/NetworkManager/NetworkManager.conf in an editor with root rights.
> Delete (or comment out with a hash #) the line that reads dns=dnsmasq.
> Restart NetworkManager via sudo service NetworkManager restart.

**Comment by zhovner** [comment]
Думаю стоит добавить информацию про dnsmasq в wiki.

**Comment by SAOPP** [comment]
У меня кстати на 17.10 не получилось ничего. Заблокированные ресурсы остаются заблокированными даже после последней рекомендации из вики... Есть у кого рабочие наработки для 17.10?

**Comment by zhovner** [comment]
Убедитесь, что у вас корректно проставляются маршруты.

**Comment by SAOPP** [comment]
Подскажите, куда копнуть для убеждения? Что конкретно нужно посмотреть? Извиняюсь за вопросы...

**Comment by SAOPP** [comment]
По пингам на все ресурсы что блокируются, все равно хожу на днс провайдера.
Здешний это Триолан, и получаю его ответ.

**Comment by SAOPP** [comment]
Странно, вроде бы все подключено, маршруты есть, но не вижу где собака зарыта.
