### ISSUE TITLE
Add Cloudflare IPs, blocked in Ukraine

### ISSUE THREAD

**Issue by Alex-302-1** [zhovner/zaborona_help#521]
These IPs are blocked in Ukraine

```
188.114.97.3
188.114.96.3
```

Tens of thousands of sites use these addresses, including Ukrainian (the list is limited to 100k sites)
https://2ip.io/domain-list-by-ip/188.114.96.3/
https://2ip.io/domain-list-by-ip/188.114.97.3/

**Comment by raddyst** [comment]
> These IPs are blocked in Ukraine
> 
> ```
> 188.114.97.3
> 188.114.96.3
> ```

![image](https://github.com/zhovner/zaborona_help/assets/8584929/9d370b0a-329e-471d-a066-a051c3011552)
![image](https://github.com/zhovner/zaborona_help/assets/8584929/7e48ea6b-7d5c-479d-909e-93332629c8f1)

**Comment by Alex-302-1** [comment]
It seems not all ISPs use IP blocking list
https://uablacklist.net/ips.txt

On my end no reply after giganet

* Wired ISP

![image](https://github.com/zhovner/zaborona_help/assets/84335470/827ad507-4d70-4af9-85c7-2805931e5828)


* Mobile ISP (Lifecell)

![image](https://github.com/zhovner/zaborona_help/assets/84335470/5fa04237-4194-48d6-8f09-98197e36e142)

But it's strange that with partially identical routes, you have it available and I don't. Giganet says that they don't filter traffic.

**Comment by raddyst** [comment]
> But it's strange that with partially identical routes, you have it available and I don't. Giganet says that they don't filter traffic.
> I don't know how significant this problem is, but for example [prozoro.net.ua](https://prozoro.net.ua/) is inaccessible to me. 

Maybe you use public dns-servers.

**Comment by Alex-302-1** [comment]
Yes, I'm also using public servers. But my private server also gives out an IP that is blocked. But with Cloudflare DNS resolves into IP that is not blocked (but I need to use my own server).

I have Keenetik router with VPN (ipsec) for NAS with torrents. Maybe it's possible to add a route for these IPs to work through my VPN?
