### ISSUE TITLE
Отваливается VPN на роутере

### ISSUE THREAD

**Issue by advokatb** [zhovner/zaborona_help#53]
Здравствуйте. Помогите понять, в чем может быть причина проблемы:
**Практически ежедневно** (иногда через день-два) падает соединение с VPN zaborona.help на прошивке Padavan (роутер Xiaomi Mi Mini)
Лог прилагаю:

> 14:01:53 openvpn-cli[3383]: 365 variation(s) on previous 10 message(s) suppressed by --mute
14:01:53 openvpn-cli[3383]: read TCPv4_CLIENT: Connection timed out (code=145)
14:01:53 openvpn-cli[3383]: Connection reset, restarting [0]
14:01:53 openvpn-cli[3383]: SIGUSR1[soft,connection-reset] received, process restarting
14:01:53 openvpn-cli[3383]: Restart pause, 5 second(s)
14:01:58 openvpn-cli[3383]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
14:01:58 openvpn-cli[3383]: Socket Buffers: R=[87380->87380] S=[16384->16384]
14:02:58 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:03:58 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:05:04 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:06:09 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:07:14 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:08:19 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:09:24 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:10:29 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:11:34 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:12:39 openvpn-cli[3383]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
14:13:44 openvpn-cli[3383]: NOTE: --mute triggered...

Похожий репорт https://4pda.ru/forum/index.php?showtopic=686221&view=findpost&p=62591288

**Comment by zvirja** [comment]
Если верить [статусу](https://status.zaborona.help/), то сейчас все сервера лежат. Нужно подождать, пока @zhovner не пофиксит :)

**Comment by zhovner** [comment]
DDOS.

**Comment by advokatb** [comment]
Снова
 > Jun 29 04:06:25 openvpn-cli[3949]: 811 variation(s) on previous 10 message(s) suppressed by --mute
Jun 29 04:06:25 openvpn-cli[3949]: read TCPv4_CLIENT: Connection timed out (code=145)
Jun 29 04:06:25 openvpn-cli[3949]: Connection reset, restarting [0]
Jun 29 04:06:25 openvpn-cli[3949]: SIGUSR1[soft,connection-reset] received, process restarting
Jun 29 04:06:25 openvpn-cli[3949]: Restart pause, 5 second(s)
Jun 29 04:06:30 openvpn-cli[3949]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Jun 29 04:06:30 openvpn-cli[3949]: Socket Buffers: R=[87380->87380] S=[16384->16384]
Jun 29 04:07:30 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:08:30 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:09:35 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:10:40 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:11:45 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:12:50 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:13:55 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:15:00 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:16:06 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known
Jun 29 04:17:11 openvpn-cli[3949]: RESOLVE: Cannot resolve host address: vpn.zaborona.help: Name or service not known

Сегодня же не было проблем у сервера?
Но у меня основной вопрос в том, как заставить VPN самостоятельно подниматься после падения. Ибо когда ВПН падает - пропадает доступ и к остальным сайтам сети, не только заблокированным.

**Comment by advokatb** [comment]
Существует ли какая-то директива в конфиге, позволяющая выполнить переподключение к серверу при обрыве соединения?
Или скрипт для роутера писать нужно?

**Comment by zhovner** [comment]
@advokatb openvpn переподключается при обрыве автоматически. Если в вашем роутере это не происходит, обращайтесь к автору прошивки.
