### ISSUE TITLE
Разве метод GoodbyeDPI работает для Украины?

### ISSUE THREAD

**Issue by kalnish** [zhovner/zaborona_help#54]
Разве метод **GoodbyeDPI** работает для Украины? Вроде у провайдеров стандартная схема блеклист по айпи и домену. Оборудование для DPI слишком дорого для них.

**Comment by zhovner** [comment]
Вроде бы у кого-то работало.

**Comment by BlackHARD94** [comment]
> Разве метод **GoodbyeDPI** работает для Украины? Вроде у провайдеров стандартная схема блэклист по айпи и домену. Оборудование для ДПИ слишком дорого для них.

Подскажите пожалуйста такой же простой обход для Украины? Впн, прокси и zaborona не всегда подходит. Нужно чтобы скорость практически не снижалась, как на GoodbyeDPI

**Comment by toxi22** [comment]
> Подскажите пожалуйста такой же простой обход для Украины? Впн, прокси и zaborona не всегда подходит. Нужно чтобы скорость практически не снижалась, как на GoodbyeDPI

Добрый день.
Нужно проверить, будет ли она вообще работать.
В начале массовых блокировок, пробовал, то она не работала лично у меня. Как сейчас обстоят дела - нужно будет проверить.
Если верить схеме работы GoodbyeDPI, как указано на картинке:
 ![11395cb0b075eea1b22804a9b669e8c6](https://github.com/zhovner/zaborona_help/assets/4610098/2f5f522e-050c-4cb0-a1df-75ddab05147f) 
То такая схема работать не будет либо будет очень плохо работать, так как ответ приходит напрямую на компьютер пользователя, а не идет обратно через GoodbyeDPI. В случае блокировок в Украине, ответ должен возвращаться тем же путем, откуда он был отправлен.
