### ISSUE TITLE
add tvzvezda.ru

### ISSUE THREAD

**Issue by journeym** [zhovner/zaborona_help#547]
добавьте телеканал звезда tvzvezda.ru
У меня сосед пенсионер с телефона смотрит, через мой вайфай )

**Comment by raddyst** [comment]
> добавьте телеканал звезда tvzvezda.ru

он и так в списке.

**Comment by journeym** [comment]
![image](https://github.com/user-attachments/assets/bddb14bf-82af-4305-84bf-ed6ea3f350ac)
Ммм нет, не подменяет IP

**Comment by raddyst** [comment]
![зображення](https://github.com/user-attachments/assets/ee58fca2-5c94-4732-8b7e-641b1273c590)

а у меня подменяет, днс нужен от забороны, а не свой.

**Comment by journeym** [comment]
А да по ходу у меня слетел, сори
