### ISSUE TITLE
Mabma.ru (love.mail.ru) забанил IP-адреса забороны

### ISSUE THREAD

**Issue by Madcatua** [zhovner/zaborona_help#59]
Причина: Из-за недобросовестного поведения некоторых неизвестных личностей или даже просто так сработал бан по IP.
Ваш IP 77.73.68.230 заблокирован
Ваш IP заблокирован по одной из причин:
с этого адреса ведется рассылка коммерческих предложений или спама
с этого адреса кто-то рассылает хамские, оскорбительные или подозрительные сообщения или комментарии в дневниках
превышена естественная частота просмотров анкет или отправки сообщений
мы подозреваем, что с этого адреса совершаются попытки взлома анкет

Если вы не делали ничего из вышеперечисленного - значит блокировка была спровоцирована вашими соседями по сети (с одного IP адреса на сайт могут приходить ваши коллеги по работе или соседи по дому). В таком случае вам необходимо обратиться к своему интернет-провайдеру и заказать услугу выделенного IP адреса.

**Comment by zhovner** [comment]
Я думаю лучше адресовать этот вопрос администрации мамбы.ру и объяснить ситуацию. 
Мы проксируем эти адреса, так как они используются для сервиса love.mail.ru который заблокирован в Украине.  

 Попросите администрацию мамбы.ру не блокировать адреса наших серверов:

```
94.242.59.156
94.242.59.126
94.242.59.92
77.73.68.230
94.242.57.109
185.22.172.185
```

**Comment by zhovner** [comment]
Вы также можете самостоятельно убрать маршрутизацию на эти сети добавив в файл конфигурации такие строки:

```
pull-filter ignore "route 193.0.170.24"
```

С помощь опции `pull-filter ignore` вы можете игнорировать любые маршруты приходящие с сервера.

**Comment by Madcatua** [comment]
Дело в том, что вместо love.mail.ru можно использовать mamba.ru,
love.rambler.ru, wamba.ru  и т.п. Которые не блокируются провайдерами.
И просить мамбу не блокировать эти адреса, как я подозреваю бесполезно. К
тому же эти адреса из России, что создает дополнительные неудобства при
автоопределении месторасположения абонента.
А в данной ситуации(попадание некоторых адресов в бан, а в будущем
подозреваю и остальных) маршрутизация этих подсетей потеряла смысл.


30 июля 2017 г., 15:35 пользователь Pavel Zhovner <notifications@github.com>
написал:

**Comment by zhovner** [comment]
Оказывается love.mail.ru теперь ссылается на другие адреса, хотя когда я настраивал он резолвился точно так же как mamba.ru. Исправлю в течение дня.

**Comment by Madcatua** [comment]
Ответ ожидаем: "К сожалению такой функции не предусмотрено".
Врут, конечно, но подозреваю, что политика компании не позволяет
администраторам добавлять адреса в антибан. Во всяком случае не по
обращению рядового пользователя. Владельца сервиса на 20 тыс клиентов тоже
вряд-ли  послушают. Тем более что  их реальных клиентов из этих 20 тысяч -
единицы. Негатива от спама будет больше, чем прибыли.
Тем более что это касается только одного(love.mail.ru) из десятков сайтов.
Так что предлагаю все же убрать анонс маршрутизации на вышеуказанные
адреса. Проблемы от этого уже есть - бан одного из адресов. И дальше будет
только хуже.  И, если в роутере добавить строчку исключения не сложно, то
под андроидом это сделать рядовому пользователю гораздо сложнее.

30 июля 2017 г. 15:28 пользователь "Pavel Zhovner" <notifications@github.com>
написал:

Я думаю лучше адресовать этот вопрос администрации мамбы.ру и объяснить
ситуацию.
Мы проксируем эти адреса, так как они используются для сервиса love.mail.ru
который заблокирован в Украине.

Попросите администрацию мамбы.ру не блокировать адреса наших серверов:

94.242.59.156
94.242.59.126
94.242.59.92
77.73.68.230
94.242.57.109
185.22.172.185

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zhovner/zaborona_help/issues/59#issuecomment-318898658>,
or mute the thread

**Comment by zhovner** [comment]
Убрал сети mabma.ru 

https://github.com/zhovner/zaborona_help/commit/f72264bb00e0d494aa3e49f6e8afa0b361d7b14d

**Comment by iatalmid** [comment]
я тоже воевал с ними по этому поводу. Бесполезно. Стандартные ответы: попросите провайдера сменить вам IP адрес. При этом похоже мои письма просто никто не читает у них
