### ISSUE TITLE
Too long DNS Lookup (2-11 seconds)

### ISSUE THREAD

**Issue by ArtemMolotov** [zhovner/zaborona_help#60]
vk.com/im
![screenshot_5](https://user-images.githubusercontent.com/22825202/29001882-82f0ce3a-7a9d-11e7-8426-7a7cbd223a80.png)
tegos.ru
![screenshot_6](https://user-images.githubusercontent.com/22825202/29001883-82f36e56-7a9d-11e7-9139-69097c005972.png)

Some XHR's on vk.com were dropped with ~20-30 seconds timeout.

**Comment by zhovner** [comment]
Не знаю. Нужно видеть к каким конкретно доменам такой долгий резолв.

**Comment by ArtemMolotov** [comment]
Я указал домены (vk.com, tegos.ru), но он такой почти для всех доменов... Если будет нужно, могу что-то затестить.

**Comment by zhovner** [comment]
Я так понимаю на скриншотах инструменты разработчика в браузере. Там суммируется время по ресурсам загружаемым со страницы. Попробуйте использовать для резолва консольную утилиту nslookup.

**Comment by ArtemMolotov** [comment]
При следующем возникновении проблемы так и сделаю, но сейчас это никак не проявляется. 
Время там приведено отдельно для резолва и загрузки (короткие цветные, можно увидеть если открыть изображения в новой вкладке, будет хорошо видно).

Возможно, нагрузка на сервер?

**Comment by zhovner** [comment]
Я имею в виду, что здесь вероятно резолвится не один домен а все с которых загружаются файлы. Если проблема больше не воспроизводится, возможно была временная проблема на сервере.
