### ISSUE TITLE
Новые айпи яндекса

### ISSUE THREAD

**Issue by byvlad** [zhovner/zaborona_help#61]
Предлагаю добавить в профиль впн новые адреса яндекс навигатора и яндекс карт, ибо яндекс поставил в приложения новые адреса, а киевстар их тоже заблокировал, а впн в свою очередь их не видит и ничего не работает.

**Comment by zhovner** [comment]
К сожалению я не могу выяснить на своей стороне эти диапазоны. Если вы скажите какие адреса нужно добавить, я сделаю это.

**Comment by m-k** [comment]
https://bgp.he.net/search?search%5Bsearch%5D=yandex&commit=Search
https://bgp.he.net/dns/yandex.ua#_ipinfo

**Comment by zhovner** [comment]
Яндекс так пытается обойти блокировки в Украине. Это адреса компании CloudFlare. Если мы их добавим, то пустим через себя половину интернета. Сейчас мы пытаемся решать эту проблему путем подмены DNS ответов, направляя запросы на реальные сети яндекса вместо Cloudflare, но пока это работает не идеально. На выходных попытаюсь исправить до конца.

**Comment by byvlad** [comment]
Понял, будем ждать :)

**Comment by m-k** [comment]
@byvlad всё готово уже, читайте блог и юзайте верные dns'ы

**Comment by zhovner** [comment]
https://medium.com/@zaborona/решение-проблем-с-yandex-ua-и-mail-ru-a954cae5156c
