### ISSUE TITLE
Провайдер McLaut блокирует сайт не находящийся в санкционном списке

### ISSUE THREAD

**Issue by AlexUnder2010** [zhovner/zaborona_help#62]
Провайдер McLaut блокирует сайт не находящийся в санкционном списке.

**Comment by zhovner** [comment]
Почему вы так решили?

**Comment by Pleskan** [comment]
Похоже, что это просто СПАМ.

**Comment by zhovner** [comment]
Советую вам задать этот вопрос своему провайдеру.
![20170822133224](https://user-images.githubusercontent.com/774290/29561813-9185c7b2-873f-11e7-9aaf-c60f7487af23.png)

**Comment by AlexUnder2010** [comment]
Понял, спасибо

**Comment by AlexUnder2010** [comment]
"К сожалению, случайно он попал в блокировки". Уже все работает.
