### ISSUE TITLE
Сброс соединения на Ubuntu дистрибутивах

### ISSUE THREAD

**Issue by GoodGuyNick** [zhovner/zaborona_help#63]
Я писал о том, что на убунте через время, а иногда сразу, прекращает открывать заблокированные ресурсы. Дополнительно протестировал на Linux Mint 18.2, результат тот же. 
Так вот, [отключение dnsmasq](https://github.com/zhovner/zaborona_help/issues/52#issuecomment-312521864) решило проблему. 
Так как я плохо разбираюсь в сетях, мне не известен источник проблемы и я не понимаю, как dnsmasq был связан со сбросом соединения к заблокированным ресурсам. 
Стоит ли такое решение проблемы со сбросом соединения добавить в вики?

**Comment by zhovner** [comment]
Вероятнее всего проблема в том, что dnsmasq продолжает использовать DNS сервера провайдера. Вы можете добавить эту информацию в Wiki статью по настройке на Ubuntu.
