### ISSUE TITLE
VPN server seems to be down

### ISSUE THREAD

**Issue by zvirja** [zhovner/zaborona_help#64]
Router is unable to connect to server:
```
TCP: connect to [AF_INET]94.242.59.126:1194 failed: Connection timed out
```

while on the [status page](https://status.zaborona.help/) everything looks fine.

**Comment by zhovner** [comment]
It looks up for me. What is you ISP?

**Comment by zvirja** [comment]
Well, you followed up a few days later only :) Issue was fixed approx after 1 hour I noticed it.
