### ISSUE TITLE
wiki for Ubuntu Linux 16.04 LTS

### ISSUE THREAD

**Issue by vladyslavstartsev** [zhovner/zaborona_help#65]
wiki работает так же и для Linux Mint 18.2 . Ну т.е. не нужно конечно экстраполироать, но как я понимаю оно будет рабоать на всех системах построенных на Ubuntu

**Comment by GoodGuyNick** [comment]
Да. Вики подходит для любого дистрибутива основанного на Ubuntu 16.04. Более того, импорт конфига на большинстве дистрибутивах линукса, более или менее похож.
