### ISSUE TITLE
Перестал поднимать соединение роутер mikrotik.

### ISSUE THREAD

**Issue by Banzaizaizai** [zhovner/zaborona_help#70]
Доброго времени суток.
собственно сабж.
в логе только одна повторяющая запись:
```
zaborona: initializing...
zaborona: connecting...
zaborona: terminating... could not resolve name
```

People.net

**Comment by mksy** [comment]
Працює.
Шукайте у себе проблему. Можливо з DNS що не так?

![image](https://user-images.githubusercontent.com/1332123/30939432-1104e4a6-a3e6-11e7-944a-4bd8b1617d44.png)

**Comment by zhovner** [comment]
Попробуйте в консоле микротика выполнить `ping vpn.zaborona.help`
У вас почему-то не резолвится этот домен. Скорее всего на самом микротике неправильно настроен DNS. 

Вы также можете указать IP адрес одного из наших серверов, вместо домена `vpn.zaborona.help`. Например `94.242.59.156`.

**Comment by Banzaizaizai** [comment]
Странно, почему DNS  слетели. прописал гугловские в статике, все побежало. Спасибо-Дякую!)
