### ISSUE TITLE
Заблокирован emlstart.com

### ISSUE THREAD

**Issue by advokatb** [zhovner/zaborona_help#72]
Здравствуйте. Не открываются ссылки из писем рассылки от интернет-магазина Rozetka.ua. Пример: [Рассылка из Rozetka.ua](http://emlstart.com/ru/v5/te_link_tracker?hash=6m4g3j3smzuexkpj64ajintmabifdhhu85z7mpsnkbigg76mn1gtznb8a8a9jdpom68iohsfu6qcxc4711x8j3xbbnbcuupo3grpoyy8rd84wx4wyarnqantgdb6gbt4uy8gcpcipa48f9mfsq4imn9pjqwguqo94qhkc9yqaspz9566xk459b65pgmfh8xgckf1mcauuumjaxyc99jjomod94jwnk9dcmsjtcue&url=http%253A%252F%252Fcdn.rozetka.com.ua%252Frozetka%252Fe%252F.eJwNzLFugzAQgOFXiW7OYHQ-sJEyZGoGmiEZKF0i--wTSEZUwSSlUd69bP_w63sBL3Oexni_DQFqIGNIiIJBpVEjBSWFQxLYQxzdkG69m_vti5Ww9taZULhQBmOYWIwUbLXVvmQtyNYrVJGMZu18RM_sjEisjFS4edMC9Qt2ftPc6aL49Fk2q109_qTwkftmPD_8lYruap882uxXO3Xt7-wxpO-W_rZOzXp-dm1IX3h58PFwgPce8gB1vi_x_Q-Iz0S0.1EXOFZiT8iGsKjE6xRGBi-a_hHE%252Fclick)
Однако открываются через VPN браузера Opera. Возможно ли добавить "к нам" этот домен в список? 
Спасибо

**Comment by zhovner** [comment]
Этот сайт вряд ли подпадает под санкции.
