### ISSUE TITLE
добавьте инструкцию для консоли linux.

### ISSUE THREAD

**Issue by pr0cess0r** [zhovner/zaborona_help#73]
1) скачайте файл конфигурации Zaborona VPN
wget https://zaborona.help/zaborona-help.ovpn
2) запустите под sudo openvpn с скачаным файлом конфигурации
sudo openvpn zaborona-help.ovpn
3) при необходимости смените dns сервер(а) в файле /etc/resolv.conf например на:
nameserver 8.8.8.8
nameserver 8.8.4.4

(если это актуально)

**Comment by zhovner** [comment]
Совет использовать DNS гугла не верный, мы не анонсируем маршруты к этим адресам, поэтому DNS запросы пойдут через вашего провайдера. Многие провайдеры, например Киевстар, перехватывает DNS запросы и редиректит их на страницу заглушки. Чтобы это обойти, важно отправлять запросы внутри VPN, поэтому мы рекомендуем использовать те DNS, которые устанавливаются нашим сервером: 
```
Первичный DNS — 74.82.42.42
Вторичный DNS — 77.88.8.8
```

Мы сами перехватываем DNS запросы, чтобы исправить проблему с Yandex.ua, подробнее об этом в нашем блоге: https://medium.com/@zaborona/%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC-%D1%81-yandex-ua-%D0%B8-mail-ru-a954cae5156c


По поводу инструкции для консоли — уверен что тем, кому нужен такой способ запуска VPN и так о нем знает. К тому же он не устанавливает DNS записи, что не очень удобно.
