### ISSUE TITLE
Ubuntu 16.04 disconnect problem.

### ISSUE THREAD

**Issue by ZikDead** [zhovner/zaborona_help#75]
Доброго времени суток. После успешного подключение к серверу:
#### Лог OpenVPN
 VPN plugin: state changed: started (4)
VPN connection: (IP Config Get) complete
#

Отключание "dnsmasq"  не помогло.
Через некоторое время соеденение убирается не пингует даже гугл, идут пакет лосы если 8.8.8.8 пингую к примеру. Домены вроде резолвятся, нслукап проверил. На компьютере где виндовс, в этой же сетке все работает как надо... Примерно аналогичная проблема с под андроида.

Добрые люди, помогите, расскажите как проанализировать ситуацию и найти в чем проблема, 2-ой день уже ищу

**Comment by zhovner** [comment]
Смотрите события в системе, например в dmesg. К сожалению я не могу угадать что у вас происходит.
