### ISSUE TITLE
Добавить на главную страницу помощи по настройке "OpenWRT LEDE (TP Link only)"

### ISSUE THREAD

**Issue by AlexUnder2010** [zhovner/zaborona_help#77]
https://github.com/zhovner/zaborona_help/wiki/OpenWRT-LEDE-(TP-Link-only)

**Comment by AlexUnder2010** [comment]
https://github.com/zhovner/zaborona_help/wiki/OpenWRT-LEDE-(TP-Link-only)

**Comment by zhovner** [comment]
Весь сайт zaborona.help выложен в этом репозитории.
Отредактируйте страницу "ручные настройки" и оформите изменения в виде pull request, тогда мне будет достаточно нажать одну кнопку, чтобы ваши изменения опубликовались.

**Comment by zhovner** [comment]
Готово.
