### ISSUE TITLE
yandex сети

### ISSUE THREAD

**Issue by alexpro** [zhovner/zaborona_help#79]
Доброго времени суток

yandex не грузится. yandex.ru переадресовывает на yandex.ua, маршрут к этой сети не передается.
Добавил маршрут к 104.16.0.0/12 (сеть для yandex.ua) - не идет через VPN.
ВК, ОК ходят нормально.

**Comment by AlexUnder2010** [comment]
Пока только так:
https://github.com/zhovner/zaborona_help/wiki/Yandex.UA

**Comment by alexpro** [comment]
Я понял. Прошу простить, что не глянул сначала вики.
Придется еще и DNS крутить, нам здесь амазоновские адреса отвечают.
Наверно, issue можно закрывать.
