### ISSUE TITLE
Конфликт адресов с диапазоном провайдера 192.168.0.0/8

### ISSUE THREAD

**Issue by AlexUnder2010** [zhovner/zaborona_help#80]
Пользователь спрашивает:

"Столкнулся со следующей проблемой при подключении к VPN Zaborona. Мой провайдер связи выдает мне IP-адрес в сети 192.168.228.хх и точно в такой же подсети один из серверов Zaborona по DHCP выдает  IPv4-адрес. Из-за этого происходит конфликт сетей и невозможно подключиться к VPN Zaborona. В логах моего роутера такие ошибки сыпятся:

Nov 23 19:30:37ndmNetwork::Interface::IP: "OpenVPN0": network 192.168.228.0/22 conflicts with interface "ISP".
Nov 23 19:30:37ndmNetwork::Interface::OpenVpn: "OpenVPN0": system failed [0xcffd04df].
Nov 23 19:30:37ndmNetwork::RoutingTable: gateway is unreachable.

Можно ли это как-то обойти? Может можно настроить чтобы сервер выдавал роутеру только IPv6-адрес или может можно подключаться к другим серверам Zaborona, которые выдают IP-адрес из другой подсети?"

**Comment by zhovner** [comment]
Наверное можно поднять еще один сервер с другим диапазоном. 
Напомните мне через пару дней.

**Comment by Engineer2007** [comment]
После установки OpenVPN с настройками по умолчанию, импорта настроек из файла конфигурации, а также дальнейшего входа в программу для обхода блокировок сайтов появляется, долго висит и не исчезает окно со следующей информацией:
Fri Dec 15 14:30:05 2017 OpenVPN 2.4.3 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jun 20 2017
Fri Dec 15 14:30:05 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Dec 15 14:30:05 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10
Fri Dec 15 14:30:06 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.59.92:1194
Fri Dec 15 14:30:06 2017 Attempting to establish TCP connection with [AF_INET]94.242.59.92:1194 [nonblock]
Fri Dec 15 14:32:07 2017 TCP: connect to [AF_INET]94.242.59.92:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:32:07 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:32:12 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.59.156:1194
Fri Dec 15 14:32:12 2017 Attempting to establish TCP connection with [AF_INET]94.242.59.156:1194 [nonblock]
Fri Dec 15 14:34:13 2017 TCP: connect to [AF_INET]94.242.59.156:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:34:13 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:34:18 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]185.22.172.185:1194
Fri Dec 15 14:34:18 2017 Attempting to establish TCP connection with [AF_INET]185.22.172.185:1194 [nonblock]
Fri Dec 15 14:36:19 2017 TCP: connect to [AF_INET]185.22.172.185:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:36:19 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:36:24 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]77.73.68.230:1194
Fri Dec 15 14:36:24 2017 Attempting to establish TCP connection with [AF_INET]77.73.68.230:1194 [nonblock]
Fri Dec 15 14:38:25 2017 TCP: connect to [AF_INET]77.73.68.230:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:38:25 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:38:30 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.59.126:1194
Fri Dec 15 14:38:30 2017 Attempting to establish TCP connection with [AF_INET]94.242.59.126:1194 [nonblock]
Fri Dec 15 14:40:31 2017 TCP: connect to [AF_INET]94.242.59.126:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:40:31 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:40:36 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.57.109:1194
Fri Dec 15 14:40:36 2017 Attempting to establish TCP connection with [AF_INET]94.242.57.109:1194 [nonblock]
Fri Dec 15 14:42:38 2017 TCP: connect to [AF_INET]94.242.57.109:1194 failed: Connection timed out (WSAETIMEDOUT)
Fri Dec 15 14:42:38 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Dec 15 14:42:43 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.59.126:1194
Fri Dec 15 14:42:43 2017 Attempting to establish TCP connection with [AF_INET]94.242.59.126:1194 [nonblock]
Возможен ли вообще обход блокировок у моего провайдера с помощью OpenVPN? Если возможен, то каким образом? Дайте, пожалуйста, ссылку на соответствующую как можно наиболее подробную информацию, или предложите наиболее оптимальный и сопоставимый с OpenVPN вариант обхода для моего случая.

**Comment by toxi22** [comment]
Это скорее всего значит, что сервера Zaborona перегружены и не могут принимать новые подключения. Пробуйте подключиться немного позднее.

**Comment by ReshetS** [comment]
Можно же создать альтернативную конфигурацию сервера с другим диапазоном сетей для тех, у кого возникают конфликты, на другом порту, к примеру 1195, и выдавать отдельным конфигом, типа https://zaborona.help/zaborona-help-alt-net.ovpn

**Comment by Engineer2007** [comment]
> Можно же создать альтернативную конфигурацию сервера с другим диапазоном сетей для тех, у кого возникают конфликты, на другом порту, к примеру 1195, и выдавать отдельным конфигом, типа https://zaborona.help/zaborona-help-alt-net.ovpn
UPD: Я у себя использую диапазон из зарезервированного для провайдеров пространства 100.64.0.0/10, но наши провайдеры тоже иногда его используют, встречал у Vodafone

У меня недостаточно квалификаций чтобы самостоятельно создавать под своего провайдера индивидуальный файл конфигурации с отличными от стандартных параметров конфигурации. Может быть кто-нибудь даст ссылку, где максимально в доступной форме разжевывается как это сделать?

**Comment by ReshetS** [comment]
@Engineer2007 я имел в виду именно конфигурацию VPN-сервера, а не клиента. Диапазон IP-адресов, выдаваемых клиенту, задаётся именно там, клиент не может на это повлиять.

Кстати, насколько я понял из [config/openvpn/zaborona2.conf](https://github.com/zhovner/zaborona_help/blob/master/config/openvpn/zaborona2.conf), такая альтернативная конфигурация уже существует, попробуйте в клиентской конфигурации поменять строчку
`remote vpn.zaborona.help`
на
`remote vpn.zaborona.help 1195`

Я не проверял, работает ли, но я так думаю, что раз уж здесь выложено, значит и на серверах имеется.

**Comment by Engineer2007** [comment]
> @Engineer2007 я имел в виду именно конфигурацию VPN-сервера, а не клиента. Диапазон IP-адресов, выдаваемых клиенту, задаётся именно там, клиент не может на это повлиять.
Кстати, насколько я понял из config/openvpn/zaborona2.conf, такая альтернативная конфигурация уже существует, попробуйте в клиентской конфигурации поменять строчку
remote vpn.zaborona.help
на
remote vpn.zaborona.help 1195
Я не проверял, работает ли, но я так думаю, что раз уж здесь выложено, значит и на серверах имеется.

Нет все равно при подключении появляется окно со следующей информацией
Fri Apr 13 17:51:26 2018 OpenVPN 2.4.5 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar  1 2018
Fri Apr 13 17:51:26 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Apr 13 17:51:26 2018 library versions: OpenSSL 1.1.0f  25 May 2017, LZO 2.10
Fri Apr 13 17:51:27 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]77.73.68.230:1195
Fri Apr 13 17:51:27 2018 Attempting to establish TCP connection with [AF_INET]77.73.68.230:1195 [nonblock]
Fri Apr 13 17:53:28 2018 TCP: connect to [AF_INET]77.73.68.230:1195 failed: Unknown error
Fri Apr 13 17:53:28 2018 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Fri Apr 13 17:53:33 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]94.242.59.126:1195
Fri Apr 13 17:53:33 2018 Attempting to establish TCP connection with [AF_INET]94.242.59.126:1195 [nonblock]

**Comment by ReshetS** [comment]
@Engineer2007 боюсь, что Ваша проблема абсолютно не связана с изначальной проблемой с конфликтом IP-адресов.

Я предложил для @zhovner вариант решения изначальной проблемы. Выделять немножко другую подсеть из 192.168.0.0/16 - не выход из положения, т.к. провайдер может всю 16-ю выдавать, поэтому лучше для альтернативной конфигурации использовать диапазон из 10.0.0.0/8, 100.64.0.0/10 или 172.16.0.0/12
Ну и расшарить альтернативную конфигурацию на сайте с пользователями

**Comment by toxi22** [comment]
У меня кстати, сеть провайдера как раз и есть: 10.2.134.0/24 - конкретно мой квартал, а вся сеть провайдера примерно как раз и будет 10.0.0.0/8. Покрайней мере раньше так было. Сейчас возможно что-то поменялось.

**Comment by ReshetS** [comment]
> У меня кстати, сеть провайдера как раз и есть: 10.2.134.0/24 - конкретно мой квартал, а вся сеть провайдера примерно как раз и будет 10.0.0.0/8. Покрайней мере раньше так было. Сейчас возможно что-то поменялось.

Если будет два варианта конфигурации, будет выбор:
- стандартная конфигурация с подсетью из 192.168.0.0/16
- альтернативная конфигурация с подсетью в одном из вышеперечисленных диапазонов.
Т.к. у Вас 10.2.134.0/24, проблем с первой конфигурацией у Вас точно не будет )

**Comment by zhovner** [comment]
Вот вам конфиг на тестовом московском сервере [srv8.zaborona-help-UDP-no-encryption.ovpn](http://zhovner.com/tmp/srv8.zaborona-help-UDP-no-encryption.ovpn). На нем используется диапазон адресов `172.19.0.0/16`.  Протокол UDP вмесо TCP как на основных серверах, а также отключено шифрование VPN трафика.
