### ISSUE TITLE
Нет доступа к Mail.ru

### ISSUE THREAD

**Issue by AlexUnder2010** [zhovner/zaborona_help#81]
Mail.ru дает иногда такие IP, к которым нет доступа. Например такой: 35.156.166.193. Заметил, что в списке маршрутов сервера нет похожей записи.

Трассировка маршрута к mail.ru [35.156.166.193]
с максимальным числом прыжков 30:

  1     2 ms    <1 мс    <1 мс  192.168.1.1
  2    10 ms     3 ms     1 ms  192.168.0.1
  3     2 ms     2 ms     2 ms  10.39.0.1
  4     3 ms     2 ms     4 ms  193.0.240.161
  5     7 ms     2 ms     3 ms  iptvnew.mclaut.com [78.137.1.10]
  6  iptvnew.mclaut.com [78.137.1.10]  сообщает: Заданный узел недоступен.

**Comment by zhovner** [comment]
Это происходит потом, что вы используете не наши DNS.
Подробнее об этой проблеме https://medium.com/@zaborona/%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC-%D1%81-yandex-ua-%D0%B8-mail-ru-a954cae5156c
