### ISSUE TITLE
Проблема при переподключении. 

### ISSUE THREAD

**Issue by ZNick86** [zhovner/zaborona_help#85]
Прежде всего хочу сказать большое спасибо  за предоставленную помощь. Я перепрошил свой  роутер  TP-LINK 3664 Archer C9 прошивкой: DD-WRT v3.0-r33525 std (10/17/17) и по вашей инструкции настроил. Всё отлично работает, но есть одно, но! Когда  пропадает у провайдера интерне будь то свет или  проблемы с кабелем, роутер сам не переподключается к OpenVPN. Как исправить  проблему переподключения при обрыве интернета?

**Comment by hova888** [comment]
Я бы на вашем месте прошил Lede прошивку. И прописал бы один скрипт из этого wiki https://github.com/zhovner/zaborona_help/wiki/OpenWRT-Chaos-Calmer-15.05.1
Вот он умеет это делать когда пропадает интернет восстановить ваш openvpn
