### ISSUE TITLE
MikroTik wiki неточность

### ISSUE THREAD

**Issue by nrlquaker** [zhovner/zaborona_help#86]
Прошу поправить [wiki](https://github.com/zhovner/zaborona_help/wiki/Mikrotik).
```
8.8.8.8
8.8.4.4
```
нужно поменять на:
```
74.82.42.42
77.88.8.8
```
как указано в #73

**Comment by zhovner** [comment]
Вы можете сделать это самостоятельно. Wiki  доступна для правок всем.

**Comment by nrlquaker** [comment]
Поправил.
