### ISSUE TITLE
Подскажите, что нужно еще донастроить в роутере, чтобы работал обход блокировок

### ISSUE THREAD

**Issue by toxi22** [zhovner/zaborona_help#91]
Доброго дня.
Настроил OpenVPN в роутере по инструкции: https://github.com/zhovner/zaborona_help/wiki/AsusWRT.
Коннект к Zaborona состоялся. В таблице маршрутизации роутера прописались маршруты к заблокированным сетям через OpenVPN. Но с клиентских устройств доступа к заблокированным сайтам нет.

Следуя инструкции выше, у меня в настройках роутера нет пункта:

> 6.2. В пункте "Интернет" меняем значение параметра "Режим DHCP запросов" с "агрессивный" на "нормальный".

А так же мне нужно было включить в роутере IPv6 в режим Passthrough, так как роутер ругался на неизвестный параметр:

> pull-filter ignore "ifconfig-ipv6 "
> pull-filter ignore "route-ipv6 "

И соответственно прекращал работу.

> Feb  3 11:33:14 openvpn[1238]: TUN/TAP TX queue length set to 100
> Feb  3 11:33:14 openvpn[1238]: do_ifconfig, tt->ipv6=1, tt->did_ifconfig_ipv6_setup=1
> Feb  3 11:33:14 openvpn[1238]: /sbin/ifconfig tun15 192.168.229.10 netmask 255.255.252.0 mtu 1500 broadcast 192.168.231.255
> Feb  3 11:33:14 openvpn[1238]: /sbin/ifconfig tun15 add 2a00:1838:30:7380::1108/112
> Feb  3 11:33:14 openvpn[1238]: Linux ifconfig inet6 failed: external program exited with error status: 1
> Feb  3 11:33:14 openvpn[1238]: Exiting due to fatal error

> Заходим на страницу 'Локальная сеть' - 'DHCP-сервер' и прописываем настройки серверов DNS, как указано на картинке.

У меня в настройках роутера есть только одно поле "IP-адрес DNS" и в него можно вписать только один DNS адрес.

Прошивка версии: 3.0.0.4.380_8120 (Стоковая)

Подключение к провайдеру у меня идет через VPN. Поэтому настройки подключения изменять нельзя, в часности DNS, чтобы направить запросы на указанные в статье DNS сервера. При проверке из роутера доступ к заблокированным сайтам, выдает следующее:

> Server:    10.2.134.1
> Address 1: 10.2.134.1 00007.isp.ua
> 
> Name:      vk.com
> Address 1: 87.240.165.80 srv80-165-240-87.vk.com
> Address 2: 87.240.182.224 srv224-182-240-87.vk.com
> Address 3: 95.213.11.181 srv181-11-213-95.vk.com
> Address 4: 87.240.129.72 srv72-129-240-87.vk.com

10.2.134.1 - Является и шлюзом и DNS-сервером в сеть провайдера

**Comment by zhovner** [comment]
К сожалению я не знаю, посоветуйтесь с автором прошивки.
