### ISSUE TITLE
помогите разобраться с доступом к mail.ru

### ISSUE THREAD

**Issue by Banzaizaizai** [zhovner/zaborona_help#92]
Доброго времени суток
такая проблема. ни mail.ru ни yandex не отвечают
роутер -  mikrotik

DNS в маршрутах прописан
отключал получение DNS от провайдера, оставлял только 8.8.8.8 и ваши - никакого результата
из терминала в winbox - все пингуется. из сети - нет. в фаерволе никаких запретов нет. с этими же правилами другая борда, но у другого провайдера работает исправно

**Comment by zhovner** [comment]
Клиенты подключенные к микротику должны использовать наши DNS, если ваш провайдер применяет блокировку по DNS, то запросы к `8.8.8.8` будут перехватываться и подменяться.

На клиенте можете выполнить команду `tracert ya.ru` и посмотреть как идет трафик. Сравнить IP адрес на который резолвится домен `ya.ru` из консоли роутера и с клиента.

**Comment by Banzaizaizai** [comment]
я удалил вообще упоминание про 8.8.8.8 DNS. оставил только ваши. работает но как-то все равно рандомно.. суть проблемы понял, буду дальше разбираться. можно закрывать
спасибо за ответ

на двух других провайдерах - никаких проблем не обнаружено
