### ISSUE TITLE
Сети Webmoney

### ISSUE THREAD

**Issue by Slamik** [zhovner/zaborona_help#97]
Здравствуйте,

В связи с блокировкой провайдерами webmoney.ru, webmoney.ua добавьте, пожалуйста, их в списки маршрутизации.

Спасибо!

**Comment by zhovner** [comment]
Добавлены сети webmoney.ru и российских сервисов webmoney. Украинские сайты не были добавлены, так как в ближайшее время они вероятнее всего будут убраны из украинских датацентров. 

Ответственный за список сетей webmoney @toxi22

Обо всех проблемах с webmoney просьба писать в эту тему.

**Comment by milanochka777** [comment]
webmoney.ru тоже не открывается с вашей помощью... и с различными расширениями типа Хола... Ждём :(

**Comment by Challenger71** [comment]
возможно не все саб-домены в списке, ниже копирну список с пруфа (читать примерно со 160-й страницы.), пусть поверят еще раз, т.к. имен много:
«www.capitaller.ru»,
«mini.webmoney.ru»,
«mini.wmtransfer.com»,
«light.webmoney.ru»,
«light.wmtransfer.com»,   «wiki.webmoney.ru»,   «webmoney.ru»,
«wmtransfer.com»,
«passport.webmoney.ru»,
«security.webmoney.ru»,
«security.wmtransfer.com»,
«exchanger.ru»,   «login.wmtransfer.com»,   «credit.webmoney.ru»,
«debt.wmtransfer.com»,
«banking.guarantee.ru»,
«banking.gdcert.com»,   «banking.wmeuro.eu»,   «webmoney.ua»,
«banks.webmoney.ru»,
«arbitrage.webmoney.ru»,
«keeper.webmoney.ru»,
«keeper.wmtransfer.com»,
«wmsc1.webmoney.ru»,
«wmsc2.webmoney.ru»,
«wmsc3.webmoney.ru»,
«wmsc4.webmoney.ru»,
«merchant.webmoney.ru»,
«merchant.wmtransfer.com»,
«telepay.webmoney.ru»,
«telepay.wmtransfer.com»,
«wm.exchanger.money»,
«events.wmtransfer.com»,
«arbitrage.webmoney.ua»,
«files.wmtransfer.com»,
«mail.wmid.com»,   «advisor.wmtransfer.com»,   «paymaster.ua»,
«elmi.ua», «wm-factor.com.ua»
[webmoney_2.pdf](https://github.com/zhovner/zaborona_help/files/2049036/webmoney_2.pdf)

**Comment by toxi22** [comment]
@milanochka777 Попробуйте отключиться и снова подключиться к Забороне, если OpenVPN установлен на ПК, либо перезагрузите роутер, если Заборона настроена у Вас на роутере.
Доступ к https://www.webmoney.ru/ должен появиться в любом случае, так как IP адреса, которые принадлежат этому домену, идут через OpenVPN

**Comment by toxi22** [comment]
@Challenger71 
Адреса украинских доменов работать не будут ни через Заборону, ни на прямую, поэтому получить доступ к украиским доменам не сможете. Украинские сайты не были добавлены, так как в ближайшее время они вероятнее всего будут убраны из украинских датацентров.

webmoney.ua
arbitrage.webmoney.ua
paymaster.ua
elmi.ua
wm-factor.com.ua

Из всего списка не работают на данный момент только домены:
wmsc1.webmoney.ru
wmsc2.webmoney.ru
wmsc3.webmoney.ru
wmsc4.webmoney.ru
Проверим и добавим при необходимости.

**Comment by serdgou** [comment]
Не смог зайти через заборону  на https://funding.webmoney.ru ,https://news.wmtransfer.com/ ,стартовая Яндекса , через Sproot отлично заходит. а так нравится заборона.

**Comment by toxi22** [comment]
Этих адресов нет в списке заблокированных, но IP адреса добавлены в Заборону.
![2018-05-30_174918](https://user-images.githubusercontent.com/4610098/40728376-a6972fbc-6432-11e8-9d19-287a42b640fe.png)
![2018-05-30_174922](https://user-images.githubusercontent.com/4610098/40728378-a6c2ac50-6432-11e8-9098-5ecd0fb2b529.png)

**Comment by zhovner** [comment]
Завтра задеплою.

**Comment by serdgou** [comment]
Все супер, Вы гений. все работает и Вебмани и Яндекс, Спасибо Вам огромное!!!

**Comment by ClassicUA** [comment]
Через SOCKS5 не работает.

**Comment by zhovner** [comment]
@ClassicUA Socks больше для ICQ и подобного. Мы не обновляем его оперативно, поэтому данные сети не добавлены в сокс пока что.

**Comment by zhovner** [comment]
@serdgou Текущие обновления не могли затронуть яндекс, так что причина ваших проблем была  в другом.

**Comment by ClassicUA** [comment]
@zhovner Почему больше для ICQ и подобного. Я пользуюсь SOCKS5 в браузере через Proxy SwitchyOmega.

**Comment by ClassicUA** [comment]
@toxi22 Скажите, пожалуйста, будут ли добавлены адреса в SOCKS5?

**Comment by zhovner** [comment]
@ClassicUA В ближайшее время добавлю.

**Comment by zhovner** [comment]
@ClassicUA добавил в socks

**Comment by DJm00n** [comment]
Заблокированные сайты из того-же "санкционного" списка СНБО, которые не отрываются:
rian.com.ua
1tv.com
domkino.tv
domkino-premium.tv
muz1.tv
vremya.tv
telecafe.ru
bober-tv.ru
kanal-o.ru
poehali.tv
katyusha.tv
karusel-tv.ru
rtr-planeta.com
russia.tv
vesti.ru
tvkultura.ru
digitalrussia.tv
vgtrk.com
mobile.vgtrk.com
i-mult.tlum.ru
multvkino.tlum.ru
100kwt.com
ntvplus.ru
tvzvezda.ru
tnt-online.ru
radiovera.ru
россиясегодня.рф
sputniknews.com
ria.ru
rsport.ria.ru
1prime.ru
realty.ria.ru
riarating.ru
inosmi.ru
nm-g.ru
5-tv.ru
ren.tv
otr-online.ru
wbc.com.ru
promedia.ru
nashe.ru
eizvestia.com
ubp.com.ua

**Comment by toxi22** [comment]
nashe.ru должно работать через Заборону. Его добавили недели две-три назад

**Comment by DJm00n** [comment]
Со стриминговыми понятно - сервис бесплатный и не резиновый, а вот новостные хотелось бы иметь возможность посещать, для полноты картины, так сказать.
В целом рассматриваю заборону как поддерживаему базу заблокированных в Украине сайтов - на случай, чтобы быстро можно было бы развернуть свой аналог с помощью чужого VPN.

**Comment by zhovner** [comment]
Применил изменения на всех серверах, проверяйте.

**Comment by antipod228** [comment]
Здравствуйте, недавно был заблокирован сервис оповещений донатов для стримеров - streamlabs.com Сам сайт работает, а сервис - нет.
Пожалуйста, добавьте его в списки маршрутизации

**Comment by bodyajoy** [comment]
start.webmoney.ru пожалуйста
https://start.webmoney.ru/?lang=ru не заходит на такой сайт

**Comment by toxi22** [comment]
Попробуйте переподключиться к Zaborona, так как сайт открывается без проблем.
![2018-08-21_085502](https://user-images.githubusercontent.com/4610098/44383132-577ac400-a520-11e8-91a1-a479bd78b6a1.png)

**Comment by bodyajoy** [comment]
переподключился. По прежнему не открывает сайт с регистрацией..

**Comment by odessky** [comment]
Добавьте http://psp.wmtransfer.com

**Comment by toxi22** [comment]
> Добавьте http://psp.wmtransfer.com

Судя по списку: https://uablacklist.net его нет в заблокированных, ни домена psp.wmtransfer.com, ни info.paymaster.ru, ни IP адреса 91.227.52.178.

Если админ сервера даст добро, то добавим адрес в Заборону.

**Comment by zhovner** [comment]
@odessky актуально еще? Стоит добавлять или адрес все-таки не блокируется?

**Comment by odessky** [comment]
в 90% случаях не блокируется

**Comment by toxi22** [comment]
> Похоже, что https://merchant.web.money тоже заблокировали.

![2018-12-08_194245](https://user-images.githubusercontent.com/4610098/49688905-cc025e80-fb21-11e8-81d2-5e52799a5ba6.png)

**Comment by Dombay** [comment]
Киевстар Webmoney Keeper Pro - где-то через 2 минуты - ошибка соединения с центром сертификации. Где-то месяц назад работало.

Может надо свежий конфиг загрузить? wiki.webmoney.ru - Тоже не открывается.

**Comment by zhovner** [comment]
@Dombay если вы скажите, какие сети нужно добавить, я добавлю. Вы можете определить по каким адресам пытается подключиться программа с помощью tcpviewer или wireshark.

**Comment by Dombay** [comment]
Отключил Open-VPN - удалось подключиться.
WebMoney.exe	10868	TCP	60880		192.168.10.185	2802		91.227.52.9	
WebMoney.exe	10868	TCP	60883		192.168.10.185	80	http	51.75.19.243	243.ip-51-75-19.eu
WebMoney.exe	10868	TCP	60891		192.168.10.185	443	https	91.227.52.246	

WIKI - не открывается.
Доступ до даного ресурсу заблоковано згідно з відповідним рішенням РНБО, 
що були введені в дію Указами Президента України №126/2018 
про застосування персональних спеціальних економічних та інших обмежувальних заходів (санкцій). 
Повний перелікресурсів, що підлягають блокуванню, розміщенно на офіційному сайті Голови держави.
Обмен пакетами с wiki.webmoney.ru [81.23.24.194] с 32 байтами данных:
Обмен пакетами с webmoney.ru [81.23.24.194] с 32 байтами данных:

**Comment by Dombay** [comment]
Уже и с вкл. Open-VPN Webmoney Keeper Pro работает...

**Comment by toxi22** [comment]
> Киевстар Webmoney Keeper Pro - где-то через 2 минуты - ошибка соединения с центром сертификации. Где-то месяц назад работало.
> 
> Может надо свежий конфиг загрузить? wiki.webmoney.ru - Тоже не открывается.

Проверил адреса по списку https://uablacklist.net - адреса не менялись.

**Comment by YuriyPonomarov** [comment]
Не авторизуется кошелек WebMoney. Нет доступа к:
https://login.wmtransfer.com - 212.118.48.16

**Comment by VitaliyS** [comment]
webmoney.ru убрали из списка маршрутов? Сейчас перекидывает на стандартную заглушку . Другие сайты из списка запрещенных работают

**Comment by YuriyPonomarov** [comment]
> webmoney.ru убрали из списка маршрутов? Сейчас перекидывает на стандартную заглушку . Другие сайты из списка запрещенных работают

у меня webmoney.ru работает нормально через zaborona help

**Comment by VitaliyS** [comment]
> > webmoney.ru убрали из списка маршрутов? Сейчас перекидывает на стандартную заглушку . Другие сайты из списка запрещенных работают
> 
> у меня webmoney.ru работает нормально через zaborona help

Уже пробовал переподключиться - без изменений

**Comment by toxi22** [comment]
У них добавилось два новых IP адреса и их еще нет в списках Забороны, но провайдеры успели их добавить с список блокировок.

**Comment by beerhack** [comment]
Нужно добавить login.web.money, он открывается без впн и в итоге там не получается авторизоваться с помощью кипера, потому что он подключен через впн, и разные ip адреса получаются.

**Comment by toxi22** [comment]
> Нужно добавить login.web.money, он открывается без впн и в итоге там не получается авторизоваться с помощью кипера, потому что он подключен через впн, и разные ip адреса получаются.

Добавим этот адрес

**Comment by toxi22** [comment]
Проверьте, пожалуйста, работу ВебМани и если будут проблемы, отпишитесь.

**Comment by zhovner** [comment]
@toxi22 еще не задеплоил, завтра с утра проверяйте.

**Comment by zhovner** [comment]
Все сети из pull request-ов  добавлены, если будут проблемы, откройте снова.

**Comment by beerhack** [comment]
> > Нужно добавить login.web.money, он открывается без впн и в итоге там не получается авторизоваться с помощью кипера, потому что он подключен через впн, и разные ip адреса получаются.
> 
> Добавим этот адрес

Наверное не добавили, потому что всё равно на него заходит с родным IP, а не через впн. И проблема та же, авторизация не получается, пишет "Настройте подключение вашего браузера и WM Keeper через одинаковый IP"

**Comment by toxi22** [comment]
> > > Нужно добавить login.web.money, он открывается без впн и в итоге там не получается авторизоваться с помощью кипера, потому что он подключен через впн, и разные ip адреса получаются.
> > 
> > 
> > Добавим этот адрес
> 
> Наверное не добавили, потому что всё равно на него заходит с родным IP, а не через впн. И проблема та же, авторизация не получается, пишет "Настройте подключение вашего браузера и WM Keeper через одинаковый IP"

Сделайте, пожалуйста, пинг со своего компьютера, на котором Вы запускаете Кипер до того сайта, на котором у Вас проблема (сайт, который у Вас открывается напрямую, а не через ВПН).
Инструкция, как сделать пинг и трассировку: https://beget.com/ru/articles/ping_tracert_site
Сделайте скриншот результата вышеприведенных команд и прикрепите его сюда, чтобы можно было проверить, на какой IP адрес Вас оправляет сайт login.web.money
Все новые адреса вебмани были добавлены на Заборону.

**Comment by beerhack** [comment]
![ping](https://user-images.githubusercontent.com/2902965/62324279-d3f87f80-b4b1-11e9-90ff-93bd52bb75b5.jpg)
Пинги не идут, я так понял. Но через браузер на ПК и с телефона сайт открывается нормально.

**Comment by toxi22** [comment]
> Пинги не идут, я так понял. Но через браузер на ПК и с телефона сайт открывается нормально.

Спасибо за информацию.
Ничего страшного, что пинги не идут. Главное, что система показала, к какому адресу она пытается подключиться.

**Comment by ClassicUA** [comment]
Не работают, Яндекс карты и погода.
